
package com.watch4net.apg.remote.databaseaccessorservice;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "DatabaseAccessor", targetNamespace = "http://www.watch4net.com/APG/Remote/DatabaseAccessorService")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface DatabaseAccessor {


    /**
     * 
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "abort", targetNamespace = "http://www.watch4net.com/APG/Remote/DatabaseAccessorService", className = "com.watch4net.apg.remote.databaseaccessorservice.Abort")
    @ResponseWrapper(localName = "abortResponse", targetNamespace = "http://www.watch4net.com/APG/Remote/DatabaseAccessorService", className = "com.watch4net.apg.remote.databaseaccessorservice.AbortResponse")
    public boolean abort();

    /**
     * 
     * @param filter
     * @return
     *     returns java.util.List<java.lang.Integer>
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(name = "period", targetNamespace = "http://www.watch4net.com/APG/Remote/DatabaseAccessorService")
    @RequestWrapper(localName = "getAvailableAggregatePeriods", targetNamespace = "http://www.watch4net.com/APG/Remote/DatabaseAccessorService", className = "com.watch4net.apg.remote.databaseaccessorservice.GetAvailableAggregatePeriods")
    @ResponseWrapper(localName = "getAvailableAggregatePeriodsResponse", targetNamespace = "http://www.watch4net.com/APG/Remote/DatabaseAccessorService", className = "com.watch4net.apg.remote.databaseaccessorservice.GetAvailableAggregatePeriodsResponse")
    public List<Integer> getAvailableAggregatePeriods(
        @WebParam(name = "filter", targetNamespace = "http://www.watch4net.com/APG/Remote/DatabaseAccessorService")
        String filter)
        throws Exception_Exception
    ;

    /**
     * 
     * @param limit
     * @param timeFilter
     * @param startTimestamp
     * @param timeZone
     * @param endTimestamp
     * @param filter
     * @return
     *     returns java.util.List<java.lang.String>
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(name = "filter", targetNamespace = "http://www.watch4net.com/APG/Remote/DatabaseAccessorService")
    @RequestWrapper(localName = "getObjectFilters", targetNamespace = "http://www.watch4net.com/APG/Remote/DatabaseAccessorService", className = "com.watch4net.apg.remote.databaseaccessorservice.GetObjectFilters")
    @ResponseWrapper(localName = "getObjectFiltersResponse", targetNamespace = "http://www.watch4net.com/APG/Remote/DatabaseAccessorService", className = "com.watch4net.apg.remote.databaseaccessorservice.GetObjectFiltersResponse")
    public List<String> getObjectFilters(
        @WebParam(name = "filter", targetNamespace = "http://www.watch4net.com/APG/Remote/DatabaseAccessorService")
        String filter,
        @WebParam(name = "start-timestamp", targetNamespace = "http://www.watch4net.com/APG/Remote/DatabaseAccessorService")
        int startTimestamp,
        @WebParam(name = "end-timestamp", targetNamespace = "http://www.watch4net.com/APG/Remote/DatabaseAccessorService")
        int endTimestamp,
        @WebParam(name = "time-zone", targetNamespace = "http://www.watch4net.com/APG/Remote/DatabaseAccessorService")
        String timeZone,
        @WebParam(name = "time-filter", targetNamespace = "http://www.watch4net.com/APG/Remote/DatabaseAccessorService")
        String timeFilter,
        @WebParam(name = "limit", targetNamespace = "http://www.watch4net.com/APG/Remote/DatabaseAccessorService")
        Integer limit)
        throws Exception_Exception
    ;

    /**
     * 
     * @param limit
     * @param pattern
     * @param property
     * @param filter
     * @return
     *     returns java.util.List<com.watch4net.apg.remote.databaseaccessorservice.Suggestion>
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(name = "suggestion", targetNamespace = "http://www.watch4net.com/APG/Remote/DatabaseAccessorService")
    @RequestWrapper(localName = "getSuggestions", targetNamespace = "http://www.watch4net.com/APG/Remote/DatabaseAccessorService", className = "com.watch4net.apg.remote.databaseaccessorservice.GetSuggestions")
    @ResponseWrapper(localName = "getSuggestionsResponse", targetNamespace = "http://www.watch4net.com/APG/Remote/DatabaseAccessorService", className = "com.watch4net.apg.remote.databaseaccessorservice.GetSuggestionsResponse")
    public List<Suggestion> getSuggestions(
        @WebParam(name = "filter", targetNamespace = "http://www.watch4net.com/APG/Remote/DatabaseAccessorService")
        String filter,
        @WebParam(name = "pattern", targetNamespace = "http://www.watch4net.com/APG/Remote/DatabaseAccessorService")
        String pattern,
        @WebParam(name = "property", targetNamespace = "http://www.watch4net.com/APG/Remote/DatabaseAccessorService")
        List<String> property,
        @WebParam(name = "limit", targetNamespace = "http://www.watch4net.com/APG/Remote/DatabaseAccessorService")
        Integer limit)
        throws Exception_Exception
    ;

    /**
     * 
     * @param timeFilter
     * @param startTimestamp
     * @param subFilter
     * @param timeZone
     * @param aggregations
     * @param period
     * @param endTimestamp
     * @param filter
     * @return
     *     returns java.util.List<com.watch4net.apg.remote.databaseaccessorservice.TimeSerie>
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(name = "timeserie", targetNamespace = "http://www.watch4net.com/APG/Remote/DatabaseAccessorService")
    @RequestWrapper(localName = "getAggregatedData", targetNamespace = "http://www.watch4net.com/APG/Remote/DatabaseAccessorService", className = "com.watch4net.apg.remote.databaseaccessorservice.GetAggregatedData")
    @ResponseWrapper(localName = "getAggregatedDataResponse", targetNamespace = "http://www.watch4net.com/APG/Remote/DatabaseAccessorService", className = "com.watch4net.apg.remote.databaseaccessorservice.GetAggregatedDataResponse")
    public List<TimeSerie> getAggregatedData(
        @WebParam(name = "filter", targetNamespace = "http://www.watch4net.com/APG/Remote/DatabaseAccessorService")
        String filter,
        @WebParam(name = "sub-filter", targetNamespace = "http://www.watch4net.com/APG/Remote/DatabaseAccessorService")
        List<String> subFilter,
        @WebParam(name = "start-timestamp", targetNamespace = "http://www.watch4net.com/APG/Remote/DatabaseAccessorService")
        int startTimestamp,
        @WebParam(name = "end-timestamp", targetNamespace = "http://www.watch4net.com/APG/Remote/DatabaseAccessorService")
        int endTimestamp,
        @WebParam(name = "time-zone", targetNamespace = "http://www.watch4net.com/APG/Remote/DatabaseAccessorService")
        String timeZone,
        @WebParam(name = "time-filter", targetNamespace = "http://www.watch4net.com/APG/Remote/DatabaseAccessorService")
        String timeFilter,
        @WebParam(name = "period", targetNamespace = "http://www.watch4net.com/APG/Remote/DatabaseAccessorService")
        int period,
        @WebParam(name = "aggregations", targetNamespace = "http://www.watch4net.com/APG/Remote/DatabaseAccessorService")
        Aggregations aggregations)
        throws Exception_Exception
    ;

    /**
     * 
     * @param filter
     * @return
     *     returns java.util.List<java.lang.String>
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(name = "accessor", targetNamespace = "http://www.watch4net.com/APG/Remote/DatabaseAccessorService")
    @RequestWrapper(localName = "getAvailableAccessors", targetNamespace = "http://www.watch4net.com/APG/Remote/DatabaseAccessorService", className = "com.watch4net.apg.remote.databaseaccessorservice.GetAvailableAccessors")
    @ResponseWrapper(localName = "getAvailableAccessorsResponse", targetNamespace = "http://www.watch4net.com/APG/Remote/DatabaseAccessorService", className = "com.watch4net.apg.remote.databaseaccessorservice.GetAvailableAccessorsResponse")
    public List<String> getAvailableAccessors(
        @WebParam(name = "filter", targetNamespace = "http://www.watch4net.com/APG/Remote/DatabaseAccessorService")
        String filter)
        throws Exception_Exception
    ;

    /**
     * 
     * @param timeFilter
     * @param startTimestamp
     * @param property
     * @param timeZone
     * @param endTimestamp
     * @param filter
     * @return
     *     returns java.util.List<com.watch4net.apg.remote.databaseaccessorservice.PropertyRecord>
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(name = "record", targetNamespace = "http://www.watch4net.com/APG/Remote/DatabaseAccessorService")
    @RequestWrapper(localName = "getDistinctPropertyRecords", targetNamespace = "http://www.watch4net.com/APG/Remote/DatabaseAccessorService", className = "com.watch4net.apg.remote.databaseaccessorservice.GetDistinctPropertyRecords")
    @ResponseWrapper(localName = "getDistinctPropertyRecordsResponse", targetNamespace = "http://www.watch4net.com/APG/Remote/DatabaseAccessorService", className = "com.watch4net.apg.remote.databaseaccessorservice.GetDistinctPropertyRecordsResponse")
    public List<PropertyRecord> getDistinctPropertyRecords(
        @WebParam(name = "filter", targetNamespace = "http://www.watch4net.com/APG/Remote/DatabaseAccessorService")
        String filter,
        @WebParam(name = "start-timestamp", targetNamespace = "http://www.watch4net.com/APG/Remote/DatabaseAccessorService")
        Integer startTimestamp,
        @WebParam(name = "end-timestamp", targetNamespace = "http://www.watch4net.com/APG/Remote/DatabaseAccessorService")
        Integer endTimestamp,
        @WebParam(name = "time-zone", targetNamespace = "http://www.watch4net.com/APG/Remote/DatabaseAccessorService")
        String timeZone,
        @WebParam(name = "time-filter", targetNamespace = "http://www.watch4net.com/APG/Remote/DatabaseAccessorService")
        String timeFilter,
        @WebParam(name = "property", targetNamespace = "http://www.watch4net.com/APG/Remote/DatabaseAccessorService")
        List<String> property)
        throws Exception_Exception
    ;

    /**
     * 
     * @param limit
     * @param timeFilter
     * @param startTimestamp
     * @param subFilter
     * @param property
     * @param timeZone
     * @param endTimestamp
     * @param filter
     * @return
     *     returns java.util.List<com.watch4net.apg.remote.databaseaccessorservice.DistinctPropertyValues>
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(name = "distinct-properties", targetNamespace = "http://www.watch4net.com/APG/Remote/DatabaseAccessorService")
    @RequestWrapper(localName = "getDistinctPropertyValues", targetNamespace = "http://www.watch4net.com/APG/Remote/DatabaseAccessorService", className = "com.watch4net.apg.remote.databaseaccessorservice.GetDistinctPropertyValues")
    @ResponseWrapper(localName = "getDistinctPropertyValuesResponse", targetNamespace = "http://www.watch4net.com/APG/Remote/DatabaseAccessorService", className = "com.watch4net.apg.remote.databaseaccessorservice.GetDistinctPropertyValuesResponse")
    public List<DistinctPropertyValues> getDistinctPropertyValues(
        @WebParam(name = "filter", targetNamespace = "http://www.watch4net.com/APG/Remote/DatabaseAccessorService")
        String filter,
        @WebParam(name = "sub-filter", targetNamespace = "http://www.watch4net.com/APG/Remote/DatabaseAccessorService")
        List<String> subFilter,
        @WebParam(name = "start-timestamp", targetNamespace = "http://www.watch4net.com/APG/Remote/DatabaseAccessorService")
        Integer startTimestamp,
        @WebParam(name = "end-timestamp", targetNamespace = "http://www.watch4net.com/APG/Remote/DatabaseAccessorService")
        Integer endTimestamp,
        @WebParam(name = "time-zone", targetNamespace = "http://www.watch4net.com/APG/Remote/DatabaseAccessorService")
        String timeZone,
        @WebParam(name = "time-filter", targetNamespace = "http://www.watch4net.com/APG/Remote/DatabaseAccessorService")
        String timeFilter,
        @WebParam(name = "property", targetNamespace = "http://www.watch4net.com/APG/Remote/DatabaseAccessorService")
        List<String> property,
        @WebParam(name = "limit", targetNamespace = "http://www.watch4net.com/APG/Remote/DatabaseAccessorService")
        Integer limit)
        throws Exception_Exception
    ;

    /**
     * 
     * @param limit
     * @param timeFilter
     * @param startTimestamp
     * @param timeZone
     * @param endTimestamp
     * @param filter
     * @return
     *     returns int
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(name = "count", targetNamespace = "http://www.watch4net.com/APG/Remote/DatabaseAccessorService")
    @RequestWrapper(localName = "getObjectCount", targetNamespace = "http://www.watch4net.com/APG/Remote/DatabaseAccessorService", className = "com.watch4net.apg.remote.databaseaccessorservice.GetObjectCount")
    @ResponseWrapper(localName = "getObjectCountResponse", targetNamespace = "http://www.watch4net.com/APG/Remote/DatabaseAccessorService", className = "com.watch4net.apg.remote.databaseaccessorservice.GetObjectCountResponse")
    public int getObjectCount(
        @WebParam(name = "filter", targetNamespace = "http://www.watch4net.com/APG/Remote/DatabaseAccessorService")
        String filter,
        @WebParam(name = "start-timestamp", targetNamespace = "http://www.watch4net.com/APG/Remote/DatabaseAccessorService")
        int startTimestamp,
        @WebParam(name = "end-timestamp", targetNamespace = "http://www.watch4net.com/APG/Remote/DatabaseAccessorService")
        int endTimestamp,
        @WebParam(name = "time-zone", targetNamespace = "http://www.watch4net.com/APG/Remote/DatabaseAccessorService")
        String timeZone,
        @WebParam(name = "time-filter", targetNamespace = "http://www.watch4net.com/APG/Remote/DatabaseAccessorService")
        String timeFilter,
        @WebParam(name = "limit", targetNamespace = "http://www.watch4net.com/APG/Remote/DatabaseAccessorService")
        Integer limit)
        throws Exception_Exception
    ;

    /**
     * 
     * @param limit
     * @param field
     * @param timeFilter
     * @param startTimestamp
     * @param subFilter
     * @param timeZone
     * @param period
     * @param endTimestamp
     * @param selectedVariable
     * @param filter
     * @return
     *     returns java.util.List<com.watch4net.apg.remote.databaseaccessorservice.TimeSeries>
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(name = "timeseries", targetNamespace = "http://www.watch4net.com/APG/Remote/DatabaseAccessorService")
    @RequestWrapper(localName = "getObjectData", targetNamespace = "http://www.watch4net.com/APG/Remote/DatabaseAccessorService", className = "com.watch4net.apg.remote.databaseaccessorservice.GetObjectData")
    @ResponseWrapper(localName = "getObjectDataResponse", targetNamespace = "http://www.watch4net.com/APG/Remote/DatabaseAccessorService", className = "com.watch4net.apg.remote.databaseaccessorservice.GetObjectDataResponse")
    public List<TimeSeries> getObjectData(
        @WebParam(name = "filter", targetNamespace = "http://www.watch4net.com/APG/Remote/DatabaseAccessorService")
        String filter,
        @WebParam(name = "sub-filter", targetNamespace = "http://www.watch4net.com/APG/Remote/DatabaseAccessorService")
        List<String> subFilter,
        @WebParam(name = "start-timestamp", targetNamespace = "http://www.watch4net.com/APG/Remote/DatabaseAccessorService")
        int startTimestamp,
        @WebParam(name = "end-timestamp", targetNamespace = "http://www.watch4net.com/APG/Remote/DatabaseAccessorService")
        int endTimestamp,
        @WebParam(name = "time-zone", targetNamespace = "http://www.watch4net.com/APG/Remote/DatabaseAccessorService")
        String timeZone,
        @WebParam(name = "time-filter", targetNamespace = "http://www.watch4net.com/APG/Remote/DatabaseAccessorService")
        String timeFilter,
        @WebParam(name = "period", targetNamespace = "http://www.watch4net.com/APG/Remote/DatabaseAccessorService")
        int period,
        @WebParam(name = "field", targetNamespace = "http://www.watch4net.com/APG/Remote/DatabaseAccessorService")
        List<Aggregation> field,
        @WebParam(name = "selected-variable", targetNamespace = "http://www.watch4net.com/APG/Remote/DatabaseAccessorService")
        List<String> selectedVariable,
        @WebParam(name = "limit", targetNamespace = "http://www.watch4net.com/APG/Remote/DatabaseAccessorService")
        Integer limit)
        throws Exception_Exception
    ;

    /**
     * 
     * @param timeFilter
     * @param startTimestamp
     * @param subFilter
     * @param property
     * @param timeZone
     * @param endTimestamp
     * @param filter
     * @return
     *     returns java.util.List<com.watch4net.apg.remote.databaseaccessorservice.ObjectPropertyValues>
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(name = "object-properties", targetNamespace = "http://www.watch4net.com/APG/Remote/DatabaseAccessorService")
    @RequestWrapper(localName = "getObjectProperties", targetNamespace = "http://www.watch4net.com/APG/Remote/DatabaseAccessorService", className = "com.watch4net.apg.remote.databaseaccessorservice.GetObjectProperties")
    @ResponseWrapper(localName = "getObjectPropertiesResponse", targetNamespace = "http://www.watch4net.com/APG/Remote/DatabaseAccessorService", className = "com.watch4net.apg.remote.databaseaccessorservice.GetObjectPropertiesResponse")
    public List<ObjectPropertyValues> getObjectProperties(
        @WebParam(name = "filter", targetNamespace = "http://www.watch4net.com/APG/Remote/DatabaseAccessorService")
        String filter,
        @WebParam(name = "sub-filter", targetNamespace = "http://www.watch4net.com/APG/Remote/DatabaseAccessorService")
        List<String> subFilter,
        @WebParam(name = "start-timestamp", targetNamespace = "http://www.watch4net.com/APG/Remote/DatabaseAccessorService")
        Integer startTimestamp,
        @WebParam(name = "end-timestamp", targetNamespace = "http://www.watch4net.com/APG/Remote/DatabaseAccessorService")
        Integer endTimestamp,
        @WebParam(name = "time-zone", targetNamespace = "http://www.watch4net.com/APG/Remote/DatabaseAccessorService")
        String timeZone,
        @WebParam(name = "time-filter", targetNamespace = "http://www.watch4net.com/APG/Remote/DatabaseAccessorService")
        String timeFilter,
        @WebParam(name = "property", targetNamespace = "http://www.watch4net.com/APG/Remote/DatabaseAccessorService")
        List<String> property)
        throws Exception_Exception
    ;

    /**
     * 
     * @param filter
     * @return
     *     returns int
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(name = "count", targetNamespace = "http://www.watch4net.com/APG/Remote/DatabaseAccessorService")
    @RequestWrapper(localName = "getStaticObjectCount", targetNamespace = "http://www.watch4net.com/APG/Remote/DatabaseAccessorService", className = "com.watch4net.apg.remote.databaseaccessorservice.GetStaticObjectCount")
    @ResponseWrapper(localName = "getStaticObjectCountResponse", targetNamespace = "http://www.watch4net.com/APG/Remote/DatabaseAccessorService", className = "com.watch4net.apg.remote.databaseaccessorservice.GetStaticObjectCountResponse")
    public int getStaticObjectCount(
        @WebParam(name = "filter", targetNamespace = "http://www.watch4net.com/APG/Remote/DatabaseAccessorService")
        String filter)
        throws Exception_Exception
    ;

    /**
     * 
     * @param filter
     * @return
     *     returns java.util.List<java.lang.String>
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(name = "filter", targetNamespace = "http://www.watch4net.com/APG/Remote/DatabaseAccessorService")
    @RequestWrapper(localName = "getStaticObjectFilters", targetNamespace = "http://www.watch4net.com/APG/Remote/DatabaseAccessorService", className = "com.watch4net.apg.remote.databaseaccessorservice.GetStaticObjectFilters")
    @ResponseWrapper(localName = "getStaticObjectFiltersResponse", targetNamespace = "http://www.watch4net.com/APG/Remote/DatabaseAccessorService", className = "com.watch4net.apg.remote.databaseaccessorservice.GetStaticObjectFiltersResponse")
    public List<String> getStaticObjectFilters(
        @WebParam(name = "filter", targetNamespace = "http://www.watch4net.com/APG/Remote/DatabaseAccessorService")
        String filter)
        throws Exception_Exception
    ;

    /**
     * 
     * @param filter
     * @return
     *     returns java.util.List<com.watch4net.apg.remote.databaseaccessorservice.Property>
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(name = "property", targetNamespace = "http://www.watch4net.com/APG/Remote/DatabaseAccessorService")
    @RequestWrapper(localName = "getAvailableProperties", targetNamespace = "http://www.watch4net.com/APG/Remote/DatabaseAccessorService", className = "com.watch4net.apg.remote.databaseaccessorservice.GetAvailableProperties")
    @ResponseWrapper(localName = "getAvailablePropertiesResponse", targetNamespace = "http://www.watch4net.com/APG/Remote/DatabaseAccessorService", className = "com.watch4net.apg.remote.databaseaccessorservice.GetAvailablePropertiesResponse")
    public List<Property> getAvailableProperties(
        @WebParam(name = "filter", targetNamespace = "http://www.watch4net.com/APG/Remote/DatabaseAccessorService")
        String filter)
        throws Exception_Exception
    ;

}
