
package com.watch4net.apg.remote.databaseaccessorservice;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "Exception", targetNamespace = "http://www.watch4net.com/APG/Remote/DatabaseAccessorService")
public class Exception_Exception
    extends java.lang.Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private com.watch4net.apg.remote.databaseaccessorservice.Exception faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public Exception_Exception(String message, com.watch4net.apg.remote.databaseaccessorservice.Exception faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public Exception_Exception(String message, com.watch4net.apg.remote.databaseaccessorservice.Exception faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: com.watch4net.apg.remote.databaseaccessorservice.Exception
     */
    public com.watch4net.apg.remote.databaseaccessorservice.Exception getFaultInfo() {
        return faultInfo;
    }

}
