#!/bin/bash
if [ -f /etc/storageos/storageos ] ; then
  /etc/storageos/storageos stop
  /etc/storageos/storageos disable
fi

/bin/systemctl stop boot-ovfenv
/bin/systemctl disable boot-ovfenv
/bin/systemctl stop nginx
/bin/systemctl disable nginx
/bin/systemctl stop syncntp
/bin/systemctl disable syncntp
/bin/systemctl stop keepalived
/bin/systemctl disable keepalived
exit 0
