
package com.emc.vipr.srm.webservice.accessors;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "DatabaseAccessor", targetNamespace = "http://www.watch4net.com/APG/Remote/DatabaseAccessorService")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface DatabaseAccessor {


    /**
     * 
     * @param filter
     * @param limit
     * @param timeZone
     * @param endTimestamp
     * @param startTimestamp
     * @param timeFilter
     * @return
     *     returns int
     * @throws ViprSrmWSException
     */
    @WebMethod
    @WebResult(name = "count", targetNamespace = "http://www.watch4net.com/APG/Remote/DatabaseAccessorService")
    @RequestWrapper(localName = "getObjectCount", targetNamespace = "http://www.watch4net.com/APG/Remote/DatabaseAccessorService", className = "com.emc.vipr.srm.webservice.accessors.GetObjectCount")
    @ResponseWrapper(localName = "getObjectCountResponse", targetNamespace = "http://www.watch4net.com/APG/Remote/DatabaseAccessorService", className = "com.emc.vipr.srm.webservice.accessors.GetObjectCountResponse")
    public int getObjectCount(
        @WebParam(name = "filter", targetNamespace = "http://www.watch4net.com/APG/Remote/DatabaseAccessorService")
        String filter,
        @WebParam(name = "start-timestamp", targetNamespace = "http://www.watch4net.com/APG/Remote/DatabaseAccessorService")
        int startTimestamp,
        @WebParam(name = "end-timestamp", targetNamespace = "http://www.watch4net.com/APG/Remote/DatabaseAccessorService")
        int endTimestamp,
        @WebParam(name = "time-zone", targetNamespace = "http://www.watch4net.com/APG/Remote/DatabaseAccessorService")
        String timeZone,
        @WebParam(name = "time-filter", targetNamespace = "http://www.watch4net.com/APG/Remote/DatabaseAccessorService")
        String timeFilter,
        @WebParam(name = "limit", targetNamespace = "http://www.watch4net.com/APG/Remote/DatabaseAccessorService")
        Integer limit)
        throws ViprSrmWSException
    ;

    /**
     * 
     * @param filter
     * @param period
     * @param timeZone
     * @param endTimestamp
     * @param aggregations
     * @param startTimestamp
     * @param timeFilter
     * @param subFilter
     * @return
     *     returns java.util.List<com.emc.vipr.srm.webservice.accessors.TimeSerie>
     * @throws ViprSrmWSException
     */
    @WebMethod
    @WebResult(name = "timeserie", targetNamespace = "http://www.watch4net.com/APG/Remote/DatabaseAccessorService")
    @RequestWrapper(localName = "getAggregatedData", targetNamespace = "http://www.watch4net.com/APG/Remote/DatabaseAccessorService", className = "com.emc.vipr.srm.webservice.accessors.GetAggregatedData")
    @ResponseWrapper(localName = "getAggregatedDataResponse", targetNamespace = "http://www.watch4net.com/APG/Remote/DatabaseAccessorService", className = "com.emc.vipr.srm.webservice.accessors.GetAggregatedDataResponse")
    public List<TimeSerie> getAggregatedData(
        @WebParam(name = "filter", targetNamespace = "http://www.watch4net.com/APG/Remote/DatabaseAccessorService")
        String filter,
        @WebParam(name = "sub-filter", targetNamespace = "http://www.watch4net.com/APG/Remote/DatabaseAccessorService")
        List<String> subFilter,
        @WebParam(name = "start-timestamp", targetNamespace = "http://www.watch4net.com/APG/Remote/DatabaseAccessorService")
        int startTimestamp,
        @WebParam(name = "end-timestamp", targetNamespace = "http://www.watch4net.com/APG/Remote/DatabaseAccessorService")
        int endTimestamp,
        @WebParam(name = "time-zone", targetNamespace = "http://www.watch4net.com/APG/Remote/DatabaseAccessorService")
        String timeZone,
        @WebParam(name = "time-filter", targetNamespace = "http://www.watch4net.com/APG/Remote/DatabaseAccessorService")
        String timeFilter,
        @WebParam(name = "period", targetNamespace = "http://www.watch4net.com/APG/Remote/DatabaseAccessorService")
        int period,
        @WebParam(name = "aggregations", targetNamespace = "http://www.watch4net.com/APG/Remote/DatabaseAccessorService")
        Aggregations aggregations)
        throws ViprSrmWSException
    ;

    /**
     * 
     * @param filter
     * @return
     *     returns java.util.List<java.lang.String>
     * @throws ViprSrmWSException
     */
    @WebMethod
    @WebResult(name = "accessor", targetNamespace = "http://www.watch4net.com/APG/Remote/DatabaseAccessorService")
    @RequestWrapper(localName = "getAvailableAccessors", targetNamespace = "http://www.watch4net.com/APG/Remote/DatabaseAccessorService", className = "com.emc.vipr.srm.webservice.accessors.GetAvailableAccessors")
    @ResponseWrapper(localName = "getAvailableAccessorsResponse", targetNamespace = "http://www.watch4net.com/APG/Remote/DatabaseAccessorService", className = "com.emc.vipr.srm.webservice.accessors.GetAvailableAccessorsResponse")
    public List<String> getAvailableAccessors(
        @WebParam(name = "filter", targetNamespace = "http://www.watch4net.com/APG/Remote/DatabaseAccessorService")
        String filter)
        throws ViprSrmWSException
    ;

    /**
     * 
     * @param filter
     * @param property
     * @param timeZone
     * @param endTimestamp
     * @param startTimestamp
     * @param timeFilter
     * @return
     *     returns java.util.List<com.emc.vipr.srm.webservice.accessors.PropertyRecord>
     * @throws ViprSrmWSException
     */
    @WebMethod
    @WebResult(name = "record", targetNamespace = "http://www.watch4net.com/APG/Remote/DatabaseAccessorService")
    @RequestWrapper(localName = "getDistinctPropertyRecords", targetNamespace = "http://www.watch4net.com/APG/Remote/DatabaseAccessorService", className = "com.emc.vipr.srm.webservice.accessors.GetDistinctPropertyRecords")
    @ResponseWrapper(localName = "getDistinctPropertyRecordsResponse", targetNamespace = "http://www.watch4net.com/APG/Remote/DatabaseAccessorService", className = "com.emc.vipr.srm.webservice.accessors.GetDistinctPropertyRecordsResponse")
    public List<PropertyRecord> getDistinctPropertyRecords(
        @WebParam(name = "filter", targetNamespace = "http://www.watch4net.com/APG/Remote/DatabaseAccessorService")
        String filter,
        @WebParam(name = "start-timestamp", targetNamespace = "http://www.watch4net.com/APG/Remote/DatabaseAccessorService")
        Integer startTimestamp,
        @WebParam(name = "end-timestamp", targetNamespace = "http://www.watch4net.com/APG/Remote/DatabaseAccessorService")
        Integer endTimestamp,
        @WebParam(name = "time-zone", targetNamespace = "http://www.watch4net.com/APG/Remote/DatabaseAccessorService")
        String timeZone,
        @WebParam(name = "time-filter", targetNamespace = "http://www.watch4net.com/APG/Remote/DatabaseAccessorService")
        String timeFilter,
        @WebParam(name = "property", targetNamespace = "http://www.watch4net.com/APG/Remote/DatabaseAccessorService")
        List<String> property)
        throws ViprSrmWSException
    ;

    /**
     * 
     * @param filter
     * @param property
     * @param limit
     * @param timeZone
     * @param endTimestamp
     * @param startTimestamp
     * @param timeFilter
     * @param subFilter
     * @return
     *     returns java.util.List<com.emc.vipr.srm.webservice.accessors.DistinctPropertyValues>
     * @throws ViprSrmWSException
     */
    @WebMethod
    @WebResult(name = "distinct-properties", targetNamespace = "http://www.watch4net.com/APG/Remote/DatabaseAccessorService")
    @RequestWrapper(localName = "getDistinctPropertyValues", targetNamespace = "http://www.watch4net.com/APG/Remote/DatabaseAccessorService", className = "com.emc.vipr.srm.webservice.accessors.GetDistinctPropertyValues")
    @ResponseWrapper(localName = "getDistinctPropertyValuesResponse", targetNamespace = "http://www.watch4net.com/APG/Remote/DatabaseAccessorService", className = "com.emc.vipr.srm.webservice.accessors.GetDistinctPropertyValuesResponse")
    public List<DistinctPropertyValues> getDistinctPropertyValues(
        @WebParam(name = "filter", targetNamespace = "http://www.watch4net.com/APG/Remote/DatabaseAccessorService")
        String filter,
        @WebParam(name = "sub-filter", targetNamespace = "http://www.watch4net.com/APG/Remote/DatabaseAccessorService")
        List<String> subFilter,
        @WebParam(name = "start-timestamp", targetNamespace = "http://www.watch4net.com/APG/Remote/DatabaseAccessorService")
        Integer startTimestamp,
        @WebParam(name = "end-timestamp", targetNamespace = "http://www.watch4net.com/APG/Remote/DatabaseAccessorService")
        Integer endTimestamp,
        @WebParam(name = "time-zone", targetNamespace = "http://www.watch4net.com/APG/Remote/DatabaseAccessorService")
        String timeZone,
        @WebParam(name = "time-filter", targetNamespace = "http://www.watch4net.com/APG/Remote/DatabaseAccessorService")
        String timeFilter,
        @WebParam(name = "property", targetNamespace = "http://www.watch4net.com/APG/Remote/DatabaseAccessorService")
        List<String> property,
        @WebParam(name = "limit", targetNamespace = "http://www.watch4net.com/APG/Remote/DatabaseAccessorService")
        Integer limit)
        throws ViprSrmWSException
    ;

    /**
     * 
     * @param filter
     * @param period
     * @param field
     * @param selectedVariable
     * @param limit
     * @param timeZone
     * @param endTimestamp
     * @param startTimestamp
     * @param timeFilter
     * @param subFilter
     * @return
     *     returns java.util.List<com.emc.vipr.srm.webservice.accessors.TimeSeries>
     * @throws ViprSrmWSException
     */
    @WebMethod
    @WebResult(name = "timeseries", targetNamespace = "http://www.watch4net.com/APG/Remote/DatabaseAccessorService")
    @RequestWrapper(localName = "getObjectData", targetNamespace = "http://www.watch4net.com/APG/Remote/DatabaseAccessorService", className = "com.emc.vipr.srm.webservice.accessors.GetObjectData")
    @ResponseWrapper(localName = "getObjectDataResponse", targetNamespace = "http://www.watch4net.com/APG/Remote/DatabaseAccessorService", className = "com.emc.vipr.srm.webservice.accessors.GetObjectDataResponse")
    public List<TimeSeries> getObjectData(
        @WebParam(name = "filter", targetNamespace = "http://www.watch4net.com/APG/Remote/DatabaseAccessorService")
        String filter,
        @WebParam(name = "sub-filter", targetNamespace = "http://www.watch4net.com/APG/Remote/DatabaseAccessorService")
        List<String> subFilter,
        @WebParam(name = "start-timestamp", targetNamespace = "http://www.watch4net.com/APG/Remote/DatabaseAccessorService")
        int startTimestamp,
        @WebParam(name = "end-timestamp", targetNamespace = "http://www.watch4net.com/APG/Remote/DatabaseAccessorService")
        int endTimestamp,
        @WebParam(name = "time-zone", targetNamespace = "http://www.watch4net.com/APG/Remote/DatabaseAccessorService")
        String timeZone,
        @WebParam(name = "time-filter", targetNamespace = "http://www.watch4net.com/APG/Remote/DatabaseAccessorService")
        String timeFilter,
        @WebParam(name = "period", targetNamespace = "http://www.watch4net.com/APG/Remote/DatabaseAccessorService")
        int period,
        @WebParam(name = "field", targetNamespace = "http://www.watch4net.com/APG/Remote/DatabaseAccessorService")
        List<Aggregation> field,
        @WebParam(name = "selected-variable", targetNamespace = "http://www.watch4net.com/APG/Remote/DatabaseAccessorService")
        List<String> selectedVariable,
        @WebParam(name = "limit", targetNamespace = "http://www.watch4net.com/APG/Remote/DatabaseAccessorService")
        Integer limit)
        throws ViprSrmWSException
    ;

    /**
     * 
     * @param filter
     * @param property
     * @param timeZone
     * @param endTimestamp
     * @param startTimestamp
     * @param timeFilter
     * @param subFilter
     * @return
     *     returns java.util.List<com.emc.vipr.srm.webservice.accessors.ObjectPropertyValues>
     * @throws ViprSrmWSException
     */
    @WebMethod
    @WebResult(name = "object-properties", targetNamespace = "http://www.watch4net.com/APG/Remote/DatabaseAccessorService")
    @RequestWrapper(localName = "getObjectProperties", targetNamespace = "http://www.watch4net.com/APG/Remote/DatabaseAccessorService", className = "com.emc.vipr.srm.webservice.accessors.GetObjectProperties")
    @ResponseWrapper(localName = "getObjectPropertiesResponse", targetNamespace = "http://www.watch4net.com/APG/Remote/DatabaseAccessorService", className = "com.emc.vipr.srm.webservice.accessors.GetObjectPropertiesResponse")
    public List<ObjectPropertyValues> getObjectProperties(
        @WebParam(name = "filter", targetNamespace = "http://www.watch4net.com/APG/Remote/DatabaseAccessorService")
        String filter,
        @WebParam(name = "sub-filter", targetNamespace = "http://www.watch4net.com/APG/Remote/DatabaseAccessorService")
        List<String> subFilter,
        @WebParam(name = "start-timestamp", targetNamespace = "http://www.watch4net.com/APG/Remote/DatabaseAccessorService")
        Integer startTimestamp,
        @WebParam(name = "end-timestamp", targetNamespace = "http://www.watch4net.com/APG/Remote/DatabaseAccessorService")
        Integer endTimestamp,
        @WebParam(name = "time-zone", targetNamespace = "http://www.watch4net.com/APG/Remote/DatabaseAccessorService")
        String timeZone,
        @WebParam(name = "time-filter", targetNamespace = "http://www.watch4net.com/APG/Remote/DatabaseAccessorService")
        String timeFilter,
        @WebParam(name = "property", targetNamespace = "http://www.watch4net.com/APG/Remote/DatabaseAccessorService")
        List<String> property)
        throws ViprSrmWSException
    ;

    /**
     * 
     * @param filter
     * @return
     *     returns int
     * @throws ViprSrmWSException
     */
    @WebMethod
    @WebResult(name = "count", targetNamespace = "http://www.watch4net.com/APG/Remote/DatabaseAccessorService")
    @RequestWrapper(localName = "getStaticObjectCount", targetNamespace = "http://www.watch4net.com/APG/Remote/DatabaseAccessorService", className = "com.emc.vipr.srm.webservice.accessors.GetStaticObjectCount")
    @ResponseWrapper(localName = "getStaticObjectCountResponse", targetNamespace = "http://www.watch4net.com/APG/Remote/DatabaseAccessorService", className = "com.emc.vipr.srm.webservice.accessors.GetStaticObjectCountResponse")
    public int getStaticObjectCount(
        @WebParam(name = "filter", targetNamespace = "http://www.watch4net.com/APG/Remote/DatabaseAccessorService")
        String filter)
        throws ViprSrmWSException
    ;

    /**
     * 
     * @param filter
     * @return
     *     returns java.util.List<java.lang.String>
     * @throws ViprSrmWSException
     */
    @WebMethod
    @WebResult(name = "filter", targetNamespace = "http://www.watch4net.com/APG/Remote/DatabaseAccessorService")
    @RequestWrapper(localName = "getStaticObjectFilters", targetNamespace = "http://www.watch4net.com/APG/Remote/DatabaseAccessorService", className = "com.emc.vipr.srm.webservice.accessors.GetStaticObjectFilters")
    @ResponseWrapper(localName = "getStaticObjectFiltersResponse", targetNamespace = "http://www.watch4net.com/APG/Remote/DatabaseAccessorService", className = "com.emc.vipr.srm.webservice.accessors.GetStaticObjectFiltersResponse")
    public List<String> getStaticObjectFilters(
        @WebParam(name = "filter", targetNamespace = "http://www.watch4net.com/APG/Remote/DatabaseAccessorService")
        String filter)
        throws ViprSrmWSException
    ;

    /**
     * 
     * @param filter
     * @return
     *     returns java.util.List<com.emc.vipr.srm.webservice.accessors.Property>
     * @throws ViprSrmWSException
     */
    @WebMethod
    @WebResult(name = "property", targetNamespace = "http://www.watch4net.com/APG/Remote/DatabaseAccessorService")
    @RequestWrapper(localName = "getAvailableProperties", targetNamespace = "http://www.watch4net.com/APG/Remote/DatabaseAccessorService", className = "com.emc.vipr.srm.webservice.accessors.GetAvailableProperties")
    @ResponseWrapper(localName = "getAvailablePropertiesResponse", targetNamespace = "http://www.watch4net.com/APG/Remote/DatabaseAccessorService", className = "com.emc.vipr.srm.webservice.accessors.GetAvailablePropertiesResponse")
    public List<Property> getAvailableProperties(
        @WebParam(name = "filter", targetNamespace = "http://www.watch4net.com/APG/Remote/DatabaseAccessorService")
        String filter)
        throws ViprSrmWSException
    ;

    /**
     * 
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "abort", targetNamespace = "http://www.watch4net.com/APG/Remote/DatabaseAccessorService", className = "com.emc.vipr.srm.webservice.accessors.Abort")
    @ResponseWrapper(localName = "abortResponse", targetNamespace = "http://www.watch4net.com/APG/Remote/DatabaseAccessorService", className = "com.emc.vipr.srm.webservice.accessors.AbortResponse")
    public boolean abort();

    /**
     * 
     * @param filter
     * @return
     *     returns java.util.List<java.lang.Integer>
     * @throws ViprSrmWSException
     */
    @WebMethod
    @WebResult(name = "period", targetNamespace = "http://www.watch4net.com/APG/Remote/DatabaseAccessorService")
    @RequestWrapper(localName = "getAvailableAggregatePeriods", targetNamespace = "http://www.watch4net.com/APG/Remote/DatabaseAccessorService", className = "com.emc.vipr.srm.webservice.accessors.GetAvailableAggregatePeriods")
    @ResponseWrapper(localName = "getAvailableAggregatePeriodsResponse", targetNamespace = "http://www.watch4net.com/APG/Remote/DatabaseAccessorService", className = "com.emc.vipr.srm.webservice.accessors.GetAvailableAggregatePeriodsResponse")
    public List<Integer> getAvailableAggregatePeriods(
        @WebParam(name = "filter", targetNamespace = "http://www.watch4net.com/APG/Remote/DatabaseAccessorService")
        String filter)
        throws ViprSrmWSException
    ;

    /**
     * 
     * @param filter
     * @param limit
     * @param timeZone
     * @param endTimestamp
     * @param startTimestamp
     * @param timeFilter
     * @return
     *     returns java.util.List<java.lang.String>
     * @throws ViprSrmWSException
     */
    @WebMethod
    @WebResult(name = "filter", targetNamespace = "http://www.watch4net.com/APG/Remote/DatabaseAccessorService")
    @RequestWrapper(localName = "getObjectFilters", targetNamespace = "http://www.watch4net.com/APG/Remote/DatabaseAccessorService", className = "com.emc.vipr.srm.webservice.accessors.GetObjectFilters")
    @ResponseWrapper(localName = "getObjectFiltersResponse", targetNamespace = "http://www.watch4net.com/APG/Remote/DatabaseAccessorService", className = "com.emc.vipr.srm.webservice.accessors.GetObjectFiltersResponse")
    public List<String> getObjectFilters(
        @WebParam(name = "filter", targetNamespace = "http://www.watch4net.com/APG/Remote/DatabaseAccessorService")
        String filter,
        @WebParam(name = "start-timestamp", targetNamespace = "http://www.watch4net.com/APG/Remote/DatabaseAccessorService")
        int startTimestamp,
        @WebParam(name = "end-timestamp", targetNamespace = "http://www.watch4net.com/APG/Remote/DatabaseAccessorService")
        int endTimestamp,
        @WebParam(name = "time-zone", targetNamespace = "http://www.watch4net.com/APG/Remote/DatabaseAccessorService")
        String timeZone,
        @WebParam(name = "time-filter", targetNamespace = "http://www.watch4net.com/APG/Remote/DatabaseAccessorService")
        String timeFilter,
        @WebParam(name = "limit", targetNamespace = "http://www.watch4net.com/APG/Remote/DatabaseAccessorService")
        Integer limit)
        throws ViprSrmWSException
    ;

    /**
     * 
     * @param filter
     * @param pattern
     * @param property
     * @param limit
     * @return
     *     returns java.util.List<com.emc.vipr.srm.webservice.accessors.Suggestion>
     * @throws ViprSrmWSException
     */
    @WebMethod
    @WebResult(name = "suggestion", targetNamespace = "http://www.watch4net.com/APG/Remote/DatabaseAccessorService")
    @RequestWrapper(localName = "getSuggestions", targetNamespace = "http://www.watch4net.com/APG/Remote/DatabaseAccessorService", className = "com.emc.vipr.srm.webservice.accessors.GetSuggestions")
    @ResponseWrapper(localName = "getSuggestionsResponse", targetNamespace = "http://www.watch4net.com/APG/Remote/DatabaseAccessorService", className = "com.emc.vipr.srm.webservice.accessors.GetSuggestionsResponse")
    public List<Suggestion> getSuggestions(
        @WebParam(name = "filter", targetNamespace = "http://www.watch4net.com/APG/Remote/DatabaseAccessorService")
        String filter,
        @WebParam(name = "pattern", targetNamespace = "http://www.watch4net.com/APG/Remote/DatabaseAccessorService")
        String pattern,
        @WebParam(name = "property", targetNamespace = "http://www.watch4net.com/APG/Remote/DatabaseAccessorService")
        List<String> property,
        @WebParam(name = "limit", targetNamespace = "http://www.watch4net.com/APG/Remote/DatabaseAccessorService")
        Integer limit)
        throws ViprSrmWSException
    ;

}
