
package com.emc.vipr.srm.webservice.accessors;

import javax.xml.ws.WebFault;

import com.emc.vipr.srm.exception.ViprSRMException;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "Exception", targetNamespace = "http://www.watch4net.com/APG/Remote/DatabaseAccessorService")
public class ViprSrmWSException
    extends ViprSRMException
{

    /**
     * 
     */
    private static final long serialVersionUID = 1082004978167667080L;
    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private com.emc.vipr.srm.webservice.accessors.Exception faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public ViprSrmWSException(String message, com.emc.vipr.srm.webservice.accessors.Exception faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public ViprSrmWSException(String message, com.emc.vipr.srm.webservice.accessors.Exception faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: com.emc.vipr.srm.webservice.accessors.Exception
     */
    public com.emc.vipr.srm.webservice.accessors.Exception getFaultInfo() {
        return faultInfo;
    }

}
