/*
 * Copyright (c) 2008-2011 EMC Corporation
 * All Rights Reserved
 */

package com.emc.storageos.coordinator.service.impl;

import java.io.*;
import java.net.InetSocketAddress;
import java.util.Iterator;
import java.util.Map.Entry;
import java.util.Properties;
import java.util.Set;

import org.apache.zookeeper.server.quorum.QuorumPeer.LearnerType;
import org.apache.zookeeper.server.quorum.QuorumPeer.QuorumServer;
import org.apache.zookeeper.server.quorum.QuorumPeerConfig;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import com.emc.storageos.coordinator.exceptions.CoordinatorException;

public class SpringQuorumPeerConfig extends QuorumPeerConfig {
    private static final Logger log = LoggerFactory.getLogger(SpringQuorumPeerConfig.class);
    private static final String SERVER_ID_FILE = "myid";
    public static final String staticCfgFileKey= "staticConfigFile";
    public static final String dynamicCfgFileKey= "dynamicConfigFile";

    private int _id;
    private Properties _properties;

    public void setMachineId(int id) {
        _id = id;
    }

    public void setProperties(Properties properties) {
        _properties = properties;
    }

    public void init() throws ConfigException, IOException {
        log.info("lbytt");
        String dataDirName = (String) _properties.get("dataDir");

        log.info("lbytt1");
        //create zk data directory if it doesn't exist
        File zkDataDir = new File(dataDirName);
        if (!zkDataDir.exists()) {
            if (!zkDataDir.mkdirs()) {
                throw CoordinatorException.fatals
                        .unableToCreateServerIDDirectories(zkDataDir.getAbsolutePath());
            }
        }

        //create zk server id file if it doesn't exist
        File serverId = new File(dataDirName, SERVER_ID_FILE);
        if (!serverId.exists()) {
            FileWriter writer = new FileWriter(serverId);
            writer.write(Integer.toString(_id));
            writer.close();
        }

        dataDir = new File(dataDirName);

        Properties staticProperties = new Properties();
        String staticConfigFileName = null;

        Properties dynamicProperties = new Properties();
        String dynamicConfigFileName = null;

        log.info("lbytt2");
        Set<String> propertyNames = _properties.stringPropertyNames();
        for (String propertyName : propertyNames) {
            String value = _properties.getProperty(propertyName);
            if (propertyName.equals(staticCfgFileKey)) {
                staticConfigFileName = dataDirName+"/"+value;
                continue;
            }

            if (propertyName.startsWith("server.")) {
                dynamicProperties.setProperty(propertyName, value);
                continue;
            }

            if (propertyName.equals(dynamicCfgFileKey)) {
                dynamicConfigFileName = dataDirName+"/"+value;
                value = dynamicConfigFileName;
            }

            staticProperties.setProperty(propertyName, value);
        }

        log.info("lbytt3");
        // Pre-process the properties to parse and remove server.* key/value
        // In future, if _properties is still used somewhere else after init, we need to clone it keep original values
        //preprocessQuorumServers(_properties);
        //parseProperties(_properties);

        //persist the static/dynamic config file
        FileOutputStream out = new FileOutputStream(staticConfigFileName);
        log.info("lbytt4");
        staticProperties.store(out, "Don't edit this file, it's auto generated by SpringQuorumPeerConfig.init()");

        out = new FileOutputStream(dynamicConfigFileName);
        dynamicProperties.store(out, "Don't edit this file, it's auto generated by SpringQuorumPeerConfig.init()");

        log.info("lby Persist the static/dynamic config file to {} and {}", staticConfigFileName, dynamicConfigFileName);
        parse(staticConfigFileName);
    }

    /*
    protected void preprocessQuorumServers(Properties zkProp) throws ConfigException {
        log.info("Preprocess quorum server from properties before send to ZK");

        Iterator<Entry<Object, Object>> iterator = _properties.entrySet().iterator();
        while (iterator.hasNext()) {
            Entry<Object, Object> entry = iterator.next();
            String key = entry.getKey().toString().trim();
            if (key.startsWith("server.")) {
                String value = entry.getValue().toString().trim();
                createQuorumServer(key, value);
                iterator.remove();
            }
        }
    }
    */

    /**
     * This logic is same as ZK 3.4.6 except splitting values with "," instead of ":"
     */
    /*
    private void createQuorumServer(String key, String value) throws ConfigException {
        int dot = key.indexOf('.');
        long sid = Long.parseLong(key.substring(dot + 1));
        String parts[] = value.split(",");
        if ((parts.length != 2) && (parts.length != 3) && (parts.length != 4)) {
            log.error(value + " does not have the form host,port or host,port,port " + " or host,port,port,type");
        }
        InetSocketAddress addr = new InetSocketAddress(parts[0], Integer.parseInt(parts[1]));
        if (parts.length == 2) {
            servers.put(Long.valueOf(sid), new QuorumServer(sid, addr));
        } else if (parts.length == 3) {
            InetSocketAddress electionAddr = new InetSocketAddress(parts[0], Integer.parseInt(parts[2]));
            servers.put(Long.valueOf(sid), new QuorumServer(sid, addr, electionAddr));
        } else if (parts.length == 4) {
            InetSocketAddress electionAddr = new InetSocketAddress(parts[0], Integer.parseInt(parts[2]));
            LearnerType type = LearnerType.PARTICIPANT;
            if (parts[3].toLowerCase().equals("observer")) {
                type = LearnerType.OBSERVER;
                observers.put(Long.valueOf(sid), new QuorumServer(sid, addr, electionAddr, type));
            } else if (parts[3].toLowerCase().equals("participant")) {
                type = LearnerType.PARTICIPANT;
                servers.put(Long.valueOf(sid), new QuorumServer(sid, addr, electionAddr, type));
            } else {
                throw new ConfigException("Unrecognised peertype: " + value);
            }
        }
    }
    */
}
