#!/bin/bash -e
#
# Copyright (c) 2014 EMC Corporation
# All Rights Reserved
#
# This software contains the intellectual property of EMC Corporation
# or is licensed to EMC Corporation from third parties.  Use of this
# software and the intellectual property contained therein is expressly
# limited to the terms and conditions of the License Agreement under which
# it is provided by or on behalf of EMC.
#
# /etc/systool
#

export PATH=/bin:/bin:/sbin:/usr/bin:/usr/sbin

. /etc/rc.status

_usage() {
    set +Ex
    echo "Usage: $0 --list"             >&2
    echo "   or: $0 --get-default"      >&2
    echo "   or: $0 --set-default name" >&2
    echo "   or: $0 --get-image name"   >&2
    echo "   or: $0 --install file"     >&2
    echo "   or: $0 --remove name"      >&2
    echo "   or: $0 --getprops"         >&2
    echo "   or: $0 --get-controller-ovfprops" >&2
    echo "   or: $0 --set-controller-ovfprops file" >&2
    echo "   or: $0 --getoverrides"     >&2
    echo "   or: $0 --setoverrides file" >&2
    echo "   or: $0 --getvdcprops"      >&2
    echo "   or: $0 --setvdcprops file" >&2
    echo "   or: $0 --getsslprops"      >&2
    echo "   or: $0 --setsslprops file" >&2
    echo "   or: $0 --get-data-revision" >&2
    echo "   or: $0 --set-data-revision file" >&2
    echo "   or: $0 --purge-data-revision" >&2
    echo "   or: $0 --reboot"           >&2
    echo "   or: $0 --poweroff"         >&2
    echo "   or: $0 --reconfig"         >&2
    echo "   or: $0 --reconfig-props [ntp] [dns] [ssh] [connectemc] [password]" >&2
    echo "   or: $0 --reconfig-security" >&2
    echo "   or: $0 --restart service"  >&2
    echo "   or: $0 --stop service"  >&2
    echo "   or: $0 --reload ntp|ssh|connectemc" >&2
    echo "   or: $0 --reconfig-coordinator observer|participant" >&2
    echo "   or: $0 --remote-systool node_id command parameter" >&2
    echo "   or: $0 --test"             >&2
    exit 2
}

_info() {
    echo "$0: Info: $*" >&2
}

_warn() {
    echo "$0: Warning: $*" >&2
}

_fatal() {
    set +Ex
    echo "$0: Error: $*" >&2
    exit 1
}

_fatal2() {
    local code=${1:-1} ; shift
    set +Ex
    echo "$0: Error: $*" >&2
    exit ${code}
}

_err_handler() {
    set +E
    _fatal "Line ${LINENO}: $(eval echo \"${BASH_COMMAND}\")"
}

_exit_handler() {
    set +E
    for action in "${on_exit_actions[@]}" ; do
        eval "${action}"
    done
}

_set_on_exit() {
    on_exit_actions=( "${@}" "${on_exit_actions[@]}" )
}

_exit_handler() {
     set +E
     for action in "${on_exit_actions[@]}" ; do 
         eval "${action}"
     done
}

_set_traps() {
     declare -a on_exit_actions
     trap '' SIGINT
     trap '' SIGTERM
     trap _exit_handler EXIT
     trap 'set +Ex ; _fatal "Line ${LINENO}: $(eval echo \"${BASH_COMMAND}\")"' ERR
     if [ -n "${*}" ] ; then set "${@}" ; fi
}

_is_appliance() {
    [ -d "${bootfs_mntp}/boot/grub/i386-pc" -o -d "${bootfs_mntp}/boot/grub2/i386-pc" ]
}

_ismounted() {
    ( set +x ; while read dev mnt type flags dummy ; do case ${#} in
        1) [ "${dev}" = "${1}" -o "${mnt}" = "${1}" ] && break ;;
        2) [ "${dev}" = "${1}" -a "${mnt}" = "${2}" ] && break ;;
    esac ; done </proc/mounts )
}

_ismounted_rw() {
    ( set +x ; while read dev mnt type flags dummy ; do case ${#} in
        1) [ "${dev}" = "${1}" -o "${mnt}" = "${1}" ] && { [[ "${flags}" =~ rw,.* ]] ; return $? ; } ;;
        2) [ "${dev}" = "${1}" -a "${mnt}" = "${2}" ] && { [[ "${flags}" =~ rw,.* ]] ; return $? ; } ;;
    esac ; done </proc/mounts )
}

_probe() {
    local dev=${1}
    udevadm settle # ; [ -e "${dev}" ] || return 1
    local retry
    for retry in 1 2 3 4 5 ; do
        local err
        err=$(dd if=${dev} of=/dev/zero count=1 2>&1) && return 0
        case "${err}" in
            *'No medium found') return 1;;
            *)                  echo "${err}" >&2;;
        esac
        sleep 1
    done
    return 1
}

_mount() {
    local dev=${@: -2: 1}
    local mnt=${@: -1: 1}
    if ! _ismounted "${dev}" "${mnt}" ; then
        mkdir -p "${mnt}"
        mount "${@}" && _set_on_exit "_umount ${mnt}"
    fi
}

_umount() {
    if _ismounted "${1}" ; then
        umount "${1}" || return $?
    fi
}

_bootfs_mount_ro() {
    if ! _is_appliance ; then
       _warn "Not a real appliance. Skipping _bootfs_mount_ro()"
    elif ! _ismounted    "${bootfs_dev}" "${bootfs_mntp}" ; then
       mkdir -p "${bootfs_mntp}"
       mount -n -t ext3 -o ro "${bootfs_dev}" "${bootfs_mntp}"
    elif _ismounted_rw "${bootfs_dev}" "${bootfs_mntp}" ; then
       mount -n -o remount,ro "${bootfs_dev}" "${bootfs_mntp}"
    fi
}

_bootfs_mount_rw() {
    [ "${bootfs_readonly}" != "true" ] || _fatal "Internal error: read-only bootfs"
    if ! _is_appliance ; then
       _warn "Not a real appliance. Skipping _bootfs_mount_rw()"
    elif ! _ismounted    "${bootfs_dev}" "${bootfs_mntp}" ; then
       mkdir -p "${bootfs_mntp}"
       mount -n -t ext3 -o rw,noatime,barrier=1 "${bootfs_dev}" "${bootfs_mntp}"
       if [ "${1}" != "no" ] ; then _set_on_exit _bootfs_mount_ro ; umask 022 ; fi
    elif ! _ismounted_rw "${bootfs_dev}" "${bootfs_mntp}" ; then
       mount -n -o remount,rw,noatime,barrier=1 "${bootfs_dev}" "${bootfs_mntp}"
       if [ "${1}" != "no" ] ; then _set_on_exit _bootfs_mount_ro ; umask 022 ; fi
    fi
}

lock_file=/tmp/${0##*/}.lock
lock_timeout=${lock_timeout:-30}

_s() {
    ( _set_traps -E && flock -s -w "${lock_timeout}" 200 && bootfs_readonly=true && _bootfs_mount_ro && "${@}" ) 200>${lock_file}
}

_x() {
    ( _set_traps -E && flock -x -w "${lock_timeout}" 200 &&                         _bootfs_mount_ro && "${@}"  ) 200>${lock_file}
}

_filter_valid() {
    local d ; while read d ; do
        if [[ "${d}" =~ ^.*-[1-9]+\.[0-9]+\.[0-9]+\.[0-9]+\.[^.]+$  ]] && [ -d "${bootfs_mntp}/${d}" ] && [ -f "${bootfs_mntp}/${d}/${bootfs_rootimg}" ] ; then echo "${d}" ; fi
    done
}

_list_all() {
    local d ; ls -t "${bootfs_mntp}" | while read d ; do
        [ -L "${bootfs_mntp}/${d}" -o "${d}" = "boot" ] || echo "${d}"
    done
}

_add_dummy_version() {
    if ! _is_appliance ; then
        cat /opt/storageos/etc/product
    fi
}

_list_valid() {
    _list_all | _filter_valid
    if [ "${DO_NOT_INCLUDE}" != "yes" ] ; then
    	_add_dummy_version
    fi
}

_get_default() {
     local symlink="${bootfs_mntp}/${bootfs_default}"
     local target=""
     if [ -L "${symlink}" ] ; then
         target=$(readlink "${symlink}")
         local d=${target%%/*}
         local v=$(echo "${d}" | _filter_valid)
         [ -n "${v}"       ] || { _warn "Internal inconsistency: ${bootfs_default} -> ${d} (Invalid directory)" ; return 0 ; }
         [ -f "${symlink}" ] || { _warn "Internal inconsistency: ${bootfs_default} -> ${d} (No such file)"      ; return 0 ; }
         echo "${v}"
     fi
     _add_dummy_version
}

_set_default() {
    local symlink="${bootfs_mntp}/${bootfs_default}"
    local image="${1}/${bootfs_rootimg}"
    [ -n "${1}"                     ] || _fatal "Invalid argument"
    local d=$(echo "${1}" | _filter_valid)
    [ -n "${d}"                     ] || _fatal "${1}: Invalid version"
    [ -d "${bootfs_mntp}/${1}"      ] || _fatal "${1}: No such version (Internal error)"
    [ -f "${bootfs_mntp}/${image}"  ] || _fatal "${1}: No such version (Corrupted?)"
    [ "${1}" = "$(_get_default)"    ] && return 0
    _bootfs_mount_rw
    rm -f "${symlink}"
    ln -s "${image}" "${symlink}"
}

_get_image() {
    local image="${1}/${bootfs_rootimg}"
    [ -n "${1}"                     ] || _fatal "Invalid argument"
    local d=$(echo "${1}" | _filter_valid)
    [ -n "${d}"                     ] || _fatal "${1}: Invalid version"
    [ -d "${bootfs_mntp}/${1}"      ] || _fatal "${1}: No such version (Internal error)"
    [ -f "${bootfs_mntp}/${image}"  ] || _fatal "${1}: No such version (Corrupted?)"
    echo "${bootfs_mntp}/${image}"
}

_remove() {
    [ -n "${1}"                   ] || _fatal "Invalid argument"
    [ "${1}" != "$(_get_default)" ] || _fatal "${1}: Can't remove ${bootfs_default}"
    _bootfs_mount_rw
    local d="${bootfs_mntp}/${1}"
    if [ -d "${d}" ] ; then  rm -r "${d}" ; fi
}

_read_file() {
    [ -f "${1}" ] || _fatal "${1}: No such file"
    echo "$(<${1})"
}

_read_override_file() {
    if [ -f "${1}" ] ; then
        cat "${1}"
    fi
}

_install() {
    local rootimg_file="${1}"
    local rootimg_mntp="/.volumes/${rootimg_file##*/}"

    # Validate the root image and get its title
    _mount -t squashfs -o ro,loop      "${rootimg_file}"   "${rootimg_mntp}"
    local menuentry && menuentry==$(_read_file "${rootimg_mntp}/${bootfs_menuentry}")
    local title     && title=$(_read_file "${rootimg_mntp}/${bootfs_title}")
    umount "${rootimg_mntp}"

    # Mount rw
    # Remove this version if exists
    # Make sure we have one empty slot
    _bootfs_mount_rw
    _remove "${title}" 

    # Sanity checks
    local bootfs_dir="${bootfs_mntp}/${title}"
    [ ! -d "${bootfs_dir}"   ] || _fatal "${bootfs_dir}: Directory exists"
    [ ! -e "${bootfs_dir}"   ] || _fatal "${bootfs_dir}: File exists"

    # Install
    mkdir -p "${bootfs_dir}"
    cp -p --no-preserve=mode "${rootimg_file}" "${bootfs_dir}/${bootfs_rootimg}"
    echo ${title}
}

_get_override_props_path() {
    [ -e "${bootfs_override_props}" ] || _fatal "${bootfs_override_props}: No such file"
    echo "${bootfs_override_props}"
}

_get_props() {
    [ ! -f "${1}" ] || ovf_props_file="${1}"
    [ ! -f "${2}" ] || override_link="${2}"
    [ ! -f "${3}" ] || dflts_file="${3}"
    _props_trymerge  
}

_get_override_props() {
    _read_override_file "${bootfs_override_props}"
}

_get_controller_props() {
    if [ -f "${bootfs_controller_props}" ] ; then
        _read_file "${bootfs_controller_props}"
    fi
}

_get_vdc_props() {
    if [ -f "${bootfs_vdc_props}" ] ; then
        _read_file "${bootfs_vdc_props}"
    fi
}

_get_ssl_props() {
    if [ -f "${bootfs_ssl_props}" ] ; then
        _read_file "${bootfs_ssl_props}"
    fi
}

_write_props_file() {
    local s && s=$(<"${1}")
    if [  -e "${2}" ] ; then
        [ "${s}" != "$(<"${2}")" ] || return 0
        _bootfs_mount_rw
        mv "${2}" "${2}~"
    else
        _bootfs_mount_rw
    fi
    mkdir -p      "${2%/*}"
    cp /dev/null  "${2}"
    chmod 600     "${2}"
    echo "${s}"  >"${2}"

}

_set_vdc_props() {
    _write_props_file "${1}" "${bootfs_vdc_props}"
}

_set_ssl_props() {
    _write_props_file "${1}" "${bootfs_ssl_props}"
}

_set_data_revision() {
    _write_props_file "${1}" "${bootfs_datarevision_props}"
}

_get_ovf_props() {
    _read_file "${ovf_props_file}"
}

_get_props_defaults() {
    _read_file "${dflts_file}"
}

_get_data_revision() {
    if [ -f "${bootfs_datarevision_props}" ] ; then
        _read_file "${bootfs_datarevision_props}"
    fi
}

_write_file_and_set_permissions() {
    mkdir -p "${1%/*}"
    cp /dev/null "${1}"
    chmod 600 "${1}"
    echo "${2}" >"${1}"
}

_set_override_props() {
    local s && s=$(<"${1}")
    if [  -e "${bootfs_override_props}" ] ; then
        [ "${s}" != "$(<"${bootfs_override_props}")" ] || return 0
        _bootfs_mount_rw
        mv "${bootfs_override_props}" "${bootfs_override_props}~"
    else
        _bootfs_mount_rw
    fi

    _write_file_and_set_permissions "${bootfs_override_props}" "${s}"   
    _props_symlink
}

_set_controller_props() {
    local s && s=$(<"${1}")
     if [  -e "${bootfs_controller_props}" ] ; then
        [ "${s}" != "$(<"${bootfs_controller_props}")" ] || return 0
        _bootfs_mount_rw
        mv "${bootfs_controller_props}" "${bootfs_controller_props}~"
    else
        _bootfs_mount_rw
    fi

    _write_file_and_set_permissions "${bootfs_controller_props}" "${s}"
}

_reboot() {
    if ! _is_appliance ; then
        _fatal2 66 "Not a real appliance. Reboot manually."
    else 
        exec /sbin/reboot
        _fatal "Failed to exec /sbin/reboot"
    fi
}

_poweroff() {
    if ! _is_appliance ; then
        _fatal2 66 "Not a real appliance. Poweroff manually."
    else
        exec /sbin/poweroff
        _fatal "Failed to exec /sbin/poweroff"
    fi
}

_reconfig() {
    exec /etc/genconfig <<EOF
$(_get_props)
EOF
    _fatal     "Failed to exec /etc/genconfig"
}

_reconfig_props() {
    exec /etc/genconfig ${1} <<EOF
$(_get_props)
EOF
    _fatal     "Failed to exec /etc/genconfig ${1}"
}

# 
# Reconfigure coordinatorsvc mode. for standby only
#
# participant - disconnect from active site and exit observer mode. becomes writable
# observer - reconnect active site and enter observer mode. becomes read-only
#
_reconfig_coordinator() {
    if [ "$(_is_dr_standby)" = "true" ] ; then
        exec /etc/genconfig "coordinator" << EOF
$(_get_props)
dr_coordinator_type=${1}
EOF
        _fatal     "Failed to exec /etc/genconfig coordinator"
   else
        _fatal     "Unsupported reconfig-coordinator operation"
   fi
}

_reconfig_security() {
    if ! _is_appliance ; then
        _fatal2 66 "Not a real appliance. Reconfig manually."
    else
	_props_symlink
        local tmp_ovf_props=${override_link}
        exec /etc/genconfig --config security <<EOF
$(_get_props ${tmp_ovf_props})
EOF
        _fatal     "Failed to exec /etc/genconfig --config security"
    fi
}

_remote_systool() {
    exec /usr/bin/ssh storageos@${1} "sudo /etc/systool ${2} ${3}"
    _fatal     "Failed to exec /usr/bin/ssh storageos@${1} \"sudo /etc/systool ${2} ${3}\""
}

_restart() {
    /usr/bin/systemctl restart storageos-${1%*svc} || _fatal2 67 "Unexpected restart ${1} failure. Error code $?"
}

_stop() {
    /usr/bin/systemctl stop storageos-${1%*svc} || _fatal2 68 "Unexpected stop ${1} failure. Error code $?"
}

#
# Restart services on standby to apply config change in _reconfig_coordinator
#
# param: participant - break connection with active site and make zk accessible
#        observer - reestablish zk connection with active site
_restart_coordinator() {
    if [ "$(_is_dr_standby)" = "true" ] ; then
        local zkdir="/data/zk"
	local tgtdir=${zkdir}/version-2
        _stop coordinatorsvc
        if [ "${1}" = "participant" ]; then
            /etc/datatool --create-snapshot /data/zk/version-2
            rm -fR /data/zk/myid
        else
            /etc/datatool --revert-snapshot /data/zk/version-2
            rm -fR /data/zk/myid
        fi

        for svc in coordinatorsvc dbsvc geodbsvc authsvc apisvc geosvc portalsvc syssvc; do
            _restart ${svc}
        done
    else
        _fatal "Unsupported reset-coordinator operation"
    fi
}

_is_dr_standby() {
    ( IFS="${nl}" ; for arg in $(<${bootfs_vdc_props}) ; do
          [ "site_is_standby" = "${arg%%=*}" ] && arg="${arg#*=}" && arg="${arg//\\n/${nl}}" && echo "${arg}" && return 0
      done
      return 1
     )
}

# Purge old data reversions
_purge_data_revision() {
    /etc/datatool --purge-unused-versions /data/db/1
    /etc/datatool --purge-unused-versions /data/geodb/1
    /etc/datatool --purge-unused-versions /data/zk/version-2
}

_rebase_zk_snapshot() {
    /etc/datatool --rebase-snapshot /data/zk/version-2
}

_reload() {
    case ${1} in
        ntp)     
            exec /usr/bin/systemctl restart ntpd ;;
        ssh)
            exec /usr/bin/systemctl restart sshd ;;
        connectemc)
            exec /usr/bin/systemctl restart connectemc ;;
        ssl)
            exec /usr/bin/systemctl restart nginx ;;
        firewall)
            exec /usr/bin/systemctl restart SuSEfirewall2 ;;
        ipsec)
            exec /usr/bin/systemctl restart ipsec ;;
        *)
            _fatal2 2 "Unsupported service type ${1}" ;;
    esac
}

_test_appliance() {
    if ! _is_appliance ; then
        _fatal2 66 "Not a real appliance."
    else
        echo "Ok" >&2
    fi
}

# This is only used for upgrade from 1.1.x to 2.x
_migrate_props() {
    if [ -f "${old_props}" ] ; then
        local oprops=$(_get_old_mutated_props)
        _props_write "${tmp_mutated_file}" "${oprops}" 
        _set_override_props "${tmp_mutated_file}"
        rm -f ${old_props} ${old_props}~ ${tmp_mutated_file} ${old_dflts_file}
    fi
}

_initialize_ovfenv_props() {
   /etc/getovfproperties --readCDROM &>/dev/null
}

_initialize_iterable_props() {
    local expanded_props="$(_expand_iterable_props "${iters_file}" "$(<${ovf_props_file})")"
    _props_append "${dflts_file}" "${expanded_props}"
    chown storageos:storageos "${dflts_file}"
}

_props_append() {
    chmod 400 "${1}" &&
    for i in ${2} ; do
        grep -q -F "${i%=*}" ${1} || echo $i >> "${1}"
    done
    sort "${1}" -o "${1}"
}

_expand_iterable_props() {
    while read line ; do
        for nodeid in $(_get_node_ids "${2}") ; do
            if [ "${nodeid}" == "standalone" ]; then
                line="${line/vipr/}"
            fi
            echo "${line//\$\{iter\}/${nodeid}}"
        done
    done < "${1}"
}

_get_node_ids() {
    if _get_ovf_property 'network_1_ipaddr' "${1}" &>/dev/null ; then
        seq --separator=' ' $(_get_ovf_property 'node_count' "${1}")
    else
        echo 'standalone'
    fi
}

_get_ovf_property() {
   ( IFS="${nl}" ; for arg in ${2} ; do
          [ "${1}" = "${arg%%=*}" ] && arg="${arg#*=}" && arg="${arg//\\n/${nl}}" && echo "${arg}" && return 0
      done
      return 1
   )
}

_initialize_props() {
    _migrate_props && 
    _props_symlink &&
    _initialize_ovfenv_props &&
    _initialize_iterable_props 
    
}

_get_old_mutated_props() {
    local dflts=$(<"${old_dflts_file}") 
    local old_properties=$(<"${old_props}") 
    local ifs="${IFS}"
    IFS="${nl}"
    local -a dlines=( ${dflts} )
    local -a olines=( ${old_properties} )
    IFS="${ifs}"
    while [ ${#olines[@]} -gt 0 -o ${#dlines[@]} -gt 0 ] ; do
        local oline=${olines[0]}
        local dline=${dlines[0]}
        local okey=${oline%%=*}
        local dkey=${dline%%=*}
        if [[ "${okey}" == "${dkey}" ]] ; then
            if [[ "${oline}" != "${dline}" ]] ; then
                ulines+=( "${oline}" )
            fi
            olines=( "${olines[@]:1}" )
            dlines=( "${dlines[@]:1}" )
        elif [[ -z "${okey}" || -z "${dkey}" ]] ; then
            break
        elif [[ "${okey}" < "${dkey}" ]] ; then
            olines=( "${olines[@]:1}" )
        else
            dlines=( "${dlines[@]:1}" )
        fi
    done
    local uline && for uline in "${ulines[@]}" ; do echo "${uline}" ; done
}


# Write the properties file with the write permissions
#
_props_write() {
   rm -f "${1}" && cp /dev/null "${1}" && chmod 400 "${1}" && echo "${2}" >>"${1}"
}

_props_trymerge() {
    _debug() {
        [ -n "${DEBUG}" ] || return 0
        local k=${1} && shift
        local x && for x in "${@}" ; do echo "*** ${k} ${x}" >&2 ; done
    }

    _merge() {
        local -a rlines=()
        while [ ${#olines[@]} -gt 0 -o ${#clines[@]} -gt 0 -o ${#dlines[@]} -gt 0 ] ; do
            _debug "*" "o=${#olines[@]} c=${#clines[@]} d=${#dlines[@]}"
            _debug "o" "${olines[@]}"
            _debug "c" "${clines[@]}"
            _debug "d" "${dlines[@]}"
            _debug "r" "${rlines[@]}"
            _debug "-" "-----------------------------------------"
            local oline=${olines[0]}
            local cline=${clines[0]}
            local dline=${dlines[0]}
            local okey=${oline%%=*}
            local ckey=${cline%%=*}
            local dkey=${dline%%=*}
            local key=
            if [[ ! -z "${okey}" ]] ; then
                key=${okey}
            elif [[ ! -z "${ckey}" ]] ; then
                key=${ckey}
            elif [[ ! -z "${dkey}" ]] ; then
                key=${dkey}
            else
                break
            fi

            if [[ "${ckey}" < "${key}" ]] ; then
                if [[ ! -z "${ckey}" ]] ; then
                    key=${ckey}
                fi
            fi
            if [[ "${dkey}" < "${key}" ]] ; then
                if [[ ! -z "${dkey}" ]] ; then
                    key=${dkey}
                fi
            fi

            if [[ "${key}" == "${okey}" ]] ; then
                rlines+=( "${oline}" )
                olines=( "${olines[@]:1}" )
                if [[ "${key}" == "${ckey}" ]] ; then
                    clines=( "${clines[@]:1}" )
                fi
                if [[ "${key}" == "${dkey}" ]] ; then
                    dlines=( "${dlines[@]:1}" )
                fi
            elif [[ "${key}" == "${ckey}" ]] ; then
                rlines+=( "${cline}" )
                clines=( "${clines[@]:1}" )
                if [[ "${key}" == "${dkey}" ]] ; then
                    dlines=( "${dlines[@]:1}" )
                fi
            else
                rlines+=( "${dline}" )
                dlines=( "${dlines[@]:1}" )
            fi
        done
        local rline && for rline in "${rlines[@]}" ; do echo "${rline}" ; done
    }

    # Three Way Merge of OVF Properties, Override Properties, and Defaults
    # - Read the properties defaults into ${dflts}, OVF properties into ${ovf_props}, and Overrides into ${overrides}
    # - The Overrides are simply cached properties that the user has mutated
    # - The OVF props have priority 1, Overrides have priority 2, amd Defaults have priority 3
    # - Echo the result of the merge
    #
    if [ ! -f "${override_link}" ] ; then
        echo >> "${override_link}"
    fi
    local dflts && dflts=$(<"${dflts_file}") && local ovf_props && ovf_props=$(<"${ovf_props_file}") && local overrides && overrides=$(<"${override_link}") && {
        local    ifs="${IFS}"
        IFS="${nl}"
        local -a dlines=( ${dflts} )
        local -a olines=( ${ovf_props} )
        local -a clines=( ${overrides} )
        IFS="${ifs}"

        echo "$(_merge)"
 
        if [ -f "${bootfs_vdc_props}" ] ; then
            cat  "${bootfs_vdc_props}"
        fi

        if [ -f "${bootfs_ssl_props}" ] ; then
            cat  "${bootfs_ssl_props}"
        fi

        if [ -f "${bootfs_datarevision_props}" ] ; then
            cat "${bootfs_datarevision_props}"
        fi 
    }
}

# Install ${override_link} -> $(/etc/systool --getoverrideprops-path)
# - Get the bootfs target and the current ${override_link} target
# - If the correct symlink is already in place do nothing
#
_props_symlink() {
    local old_target && old_target=$(readlink "${override_link}") || old_target=""
    local new_target=${bootfs_override_props}
    if ! new_target=$(_get_override_props_path 2>/dev/null) ; then
        :
    elif [ "${old_target}" = "${new_target}" ] ; then
        return 0
    else
        rm -f "${override_link}" && ln -s "${new_target}" "${override_link}"
    fi
}

_install_baremetal() {
    # mount target bootfs partition
    _mount -t ext3 ${bootfs_dev} ${bootfs_mntp}

    # install rootimg
    _install ${1}

    # install default softlink to rootimg
    default=$(_list_valid)
    _set_default ${default}
   
    # install specific grub.cfg for installed env
    local bootfs_src_mntp="/.volumes/bootfs"  # cdrom bootfs mount point while installing via cdrom
    cp -p ${bootfs_src_mntp}/boot/grub/grub.cfg.installed ${bootfs_mntp}/boot/grub2/grub.cfg
}

_get_bootfs_dev() {
    echo "${bootfs_dev}"
}

_is_appliance_wrapper() {
    _is_appliance && echo "true" || echo "false"
}

# Defaults
BOOTFS_UUID="3c426f75-726e-6520-2f62-6f6f7466733e"
bootfs_dev=$(/sbin/findfs UUID=${BOOTFS_UUID} 2>/dev/null) || bootfs_dev='/dev/sda1'
bootfs_mntp=${bootfs_mntp:-'/.volumes/bootfs'}
bootfs_vdc_props=${bootfs_vdc_props:-${bootfs_mntp}/etc/vdcconfig.properties}
bootfs_ssl_props=${bootfs_ssl_props:-${bootfs_mntp}/etc/ssl.properties}
bootfs_datarevision_props=${bootfs_datarevision_props:-${bootfs_mntp}/etc/datarevision.properties}
override_props='config-override.properties'
bootfs_override_props=${bootfs_mntp}/etc/${override_props}
override_link='/etc/'${override_props}
bootfs_max_versions=${bootfs_max_versions:-3}
bootfs_default="default"
old_props='/.volumes/bootfs/etc/ovf-env.properties'
old_dflts_file='/etc/patch-props.defaults'
dflts_file='/etc/config.defaults'
ovf_props_file='/etc/ovfenv.properties'
ssl_props_file='/etc/ssl.properties'
iters_file='/etc/.iterable.properties'
props_temp='/tmp/config.properties'
tmp_mutated_file='/tmp/mutated.properties'
controller_props='controller-ovf.properties'
bootfs_controller_props='/.volumes/bootfs/etc/'${controller_props}
nl='
'

# These names must match mkrootfs.sh
bootfs_title="label"
bootfs_menuentry="boot"
bootfs_rootimg="rootimg"

DO_NOT_INCLUDE="no"

rc_reset

# Parse flags and hacks
while [ $# -gt 0 ] ; do
    case ${1} in
        -x|--xtrace|--debug)
            set -x                ; shift ; continue ;;
        --bootfs-dev=*)
            bootfs_dev="${1#*=}"  ; shift ; continue ;;
        --bootfs-mntp=*)
            bootfs_mntp="${1#*=}" ; shift ; continue ;;
        --DO_NOT_INCLUDE=*)
            DO_NOT_INCLUDE="${1#*=}" ; shift ; continue ;;
        *)
            break ;;
    esac
done

# Parse options
#_set_traps -E
case ${#} in
    1)  case ${1} in
            --test)                   _test_appliance ;;
            --reboot)                 _reboot ;;
            --poweroff)               _poweroff ;;
            --reconfig)               _x _reconfig ;;
            --reconfig-security)      _x _reconfig_security ;;
            --list)                   _s _list_valid ;;
            --get-default)            _s _get_default ;;
            --getprops)               _s _get_props   ;;
            --getoverrides)           _s _get_override_props ;;
            --get-controller-ovfprops) _s _get_controller_props ;;            
            --getvdcprops)            _s _get_vdc_props ;;
            --getsslprops)            _s _get_ssl_props ;;
            --get-data-revision)      _s _get_data_revision ;;
            --purge-data-revision)    _s _purge_data_revision ;;
            --rebase-zk-snapshot)     _s _rebase_zk_snapshot ;;
            --getbootfsdev)           _s _get_bootfs_dev ;;
            --initializeprops)        _x _initialize_props ;;
            --remount-rw)             _x _bootfs_mount_rw "no" ;;
            --remount-ro)             _x true ;;
            --is-appliance)           _s _is_appliance_wrapper ;;
            *)                        _usage
        esac;;
    2)  case ${1} in
            --set-default)            _x _set_default          "${2}" ;;
            --install)                _x _install              "${2}" ;;
            --install-baremetal)      _x _install_baremetal    "${2}" ;;
            --get-image)              _s _get_image            "${2}" ;;
            --remove)                 _x _remove               "${2}" ;;
            --setoverrides)           _x _set_override_props   "${2}" ;;
            --set-controller-ovfprops) _x _set_controller_props "${2}" ;;            
            --setvdcprops)            _x _set_vdc_props        "${2}" ;;
            --setsslprops)            _x _set_ssl_props        "${2}" ;;
            --set-data-revision)      _x _set_data_revision    "${2}" ;;
            --restart)                _x _restart              "${2}" ;;
            --stop)                   _x _stop                 "${2}" ;;
            --reconfig-props)         _x _reconfig_props       "${2}" ;;
            --reload)                 _x _reload               "${2}" ;;
            --reconfig-coordinator)   _x _reconfig_coordinator "${2}" ;;
            --restart-coordinator)    _x _restart_coordinator  "${2}" ;;
            *)                        _usage
        esac;;
    4)  case ${1} in 
            --getprops)               _s _get_props      "${2}" "${3}" "${4}" ;;
            --remote-systool)         _s _remote_systool "${2}" "${3}" "${4}" ;;
            *)                        _usage
        esac;;
    *)  _usage
esac

rc_exit
