#!/bin/bash
#
# Copyright (c) 2015 EMC Corporation
# All Rights Reserved
#
# This software contains the intellectual property of EMC Corporation
# or is licensed to EMC Corporation from third parties.  Use of this
# software and the intellectual property contained therein is expressly
# limited to the terms and conditions of the License Agreement under which
# it is provided by or on behalf of EMC.

# This script is used to clear table data and index once.
# It won't drop table, after running this script successfully, the table is empty, still exists.
# It won't result in inconsistency between data end index either, because it takes care of both.
# It can clear multiple tables once by running "clear_table <table_name1> <table_name2> <table_name3> ..."
#
# NOTE that: this script doesn't guarantee tables are cleared successfully.
# Dependencies on tables would result in failures.

_usage() {
    echo "Usage: $0 [option] | [<table_name1> <table_name2> <table_name3> ...]"
    echo "This script is used for clear table (along with related index)."
    echo "For further details, please refer to top comment in script."
    echo ""
    echo "Options:"
    echo "    -h, --help        display help message ande exit"
}

_cleanup() {
    rm -f ${TMP_FILE}
}

if [ "$1" == "" -o "$1" == "-h" -o "$1" == "--help" ] ; then
    _usage
    exit 2
fi

TMP_FILE=$(mktemp)

trap _cleanup EXIT
trap _cleanup ERR

for table in $@ ; do
    echo "Checking ${table} ..."
    eval /opt/storageos/bin/dbutils list ${table} | grep "id:" | awk '{print $2}' > ${TMP_FILE}
    [ -s ${TMP_FILE} ] && eval /opt/storageos/bin/dbutils delete ${table} -file ${TMP_FILE}
done

_cleanup