#!/bin/bash
# alien added permissions fixup code
chown 'storageos:storageos' '/data/db'
chown 'storageos:storageos' '/data/geodb'
chown 'storageos:storageos' '/data/zk'
chown 'storageos:storageos' '/etc/.iterable.properties'
chown 'storageos:storageos' '/etc/.ovfenv.properties'
chown 'storageos:storageos' '/etc/config.defaults'
chown 'storageos:storageos' '/object/rmt'
chown -R 'storageos:storageos' '/opt/storageos'
chown -R 'storageos:storageos' '/var/run/storageos'
chmod 500 /etc/nginx/nginx.wrapper

/sbin/ldconfig /opt/storageos/lib
/bin/systemctl enable storageos-installer
/bin/systemctl enable keepalived
/bin/systemctl enable boot-ovfenv
/bin/systemctl enable nginx
/etc/storageos/storageos enable

if [ -z "${DO_NOT_START}" ] ; then
    /etc/storageos/boot-ovfenv start
    /bin/systemctl start keepalived
    /bin/systemctl start nginx 
    /etc/storageos/storageos start
fi

exit 0
