#!/bin/bash
if [ -f /etc/storageos/storageos ] ; then
  /etc/storageos/storageos stop
  /etc/storageos/storageos disable
fi

service keepalived stop
stop nginx

#stop boot-ovfenv
#disable boot-ovfenv
#disable nginx
#stop syncntp
#disable syncntp
#disable keepalived
exit 0
