#!/bin/sh
export tenant=`tenant root`
export project=sim
source subs/run
source subs/hosts
export macaddr=50:54:54:54:57:57

# host_create_4i Function to create a host.
# $1 = host name, $2 = cluster id
# $3 = arg to pwwn for first initiator,
# $4 = arg to pwwn for second initiator
# $5 = arg to pwwn for third initiator
# $6 = arg to pwwn for fourth initiator
# $7 = network to add first/second initiator to
# $8 = network to add third/fourth initiator to

#NETA=FABRIC_losam082-fabric
#NETB=FABRIC_vplex154nbr2
NETA=VSAN_11
NETB=VSAN_12

#FABRIC_losam017_FID_20-10:00:00:27:f8:58:f6:c0 urn:storageos:Network:e5ca8f0c-3e0c-44e1-8bf5-f9e48a52ac2f:vdc1
#FABRIC_vplex154nbr2 urn:storageos:Network:8cbf5640-16c8-48b2-b726-46d52ead233e:vdc1
#FABRIC_losam082-fabric urn:storageos:Network:e70c2272-03bc-46ce-8db8-76effb14a44d:vdc1

cluster_create 16yhosts
clusterId=$(cluster list $tenant | grep 16yhosts | awk ' { print $4; }')

host_create_4i host16ya $clusterId 00 01 02 03 $NETA $NETB
host_create_4i host16yb $clusterId 04 05 06 07 $NETA $NETB
host_create_4i host16yc $clusterId 08 09 0A 0B $NETA $NETB
host_create_4i host16yd $clusterId 0C 0D 0E 0F $NETA $NETB
host_create_4i host16ye $clusterId 10 11 12 13 $NETA $NETB
host_create_4i host16yf $clusterId 14 15 16 17 $NETA $NETB
host_create_4i host16yg $clusterId 18 19 1A 1B $NETA $NETB
host_create_4i host16yh $clusterId 1C 1D 1E 1F $NETA $NETB
host_create_4i host16yi $clusterId 20 21 22 23 $NETA $NETB
host_create_4i host16yj $clusterId 24 25 26 27 $NETA $NETB
host_create_4i host16yk $clusterId 28 29 2A 2B $NETA $NETB
host_create_4i host16yl $clusterId 2C 2D 2E 2F $NETA $NETB
host_create_4i host16ym $clusterId 30 31 32 33 $NETA $NETB
host_create_4i host16yn $clusterId 34 35 36 37 $NETA $NETB
host_create_4i host16yo $clusterId 38 39 3A 3B $NETA $NETB
host_create_4i host16yp $clusterId 3C 3D 3E 3F $NETA $NETB
