#!/usr/bin/python
#
# Copyright (c) 2015 EMC Corporation
# All Rights Reserved
#

import argparse
import sys
import os
from bourne import *

#----------------------------------------------------------------------
# catalog cli functions
#----------------------------------------------------------------------

def catalog_order(args):
    bourne.connect(args.ip)
    order = bourne.catalog_order(args.service, args.tenant, args.parameters) 
    print order

#----------------------------------------------------------------------
# command-line parsing
#----------------------------------------------------------------------

try:
    bourne_ip = os.environ['BOURNE_IPADDR']
except:
    bourne_ip = 'localhost'

# catalog <cmd> <cmd_args>  [--ip ipaddr]
parser = argparse.ArgumentParser(description = 'Bourne catalog cli usage.')
parser.add_argument('cmd', help = 'cmd = (create | delete | show | list )')
parser.add_argument('--ip',	metavar = 'ipaddr',	help = 'IP address of bourne', default=bourne_ip)

# catalog order service tenant parameters
order = argparse.ArgumentParser(parents = [parser], conflict_handler='resolve')
order.add_argument('service',            help = 'label for the catalog service')
order.add_argument('tenant', help = 'tenant for the catalog service')
order.add_argument('parameters',           help = 'parameters for executing the catalog service')


#----------------------------------------------------------------------
# Main script
#----------------------------------------------------------------------

try:
    if (len(sys.argv) > 1):
        cmd = sys.argv[1]
    else:
        cmd = None

    bourne = Bourne()

    if   (cmd == "order"):
        args = order.parse_args()
        catalog_order(args)
    else:
        parser.print_help()
except:
    raise
