#!/bin/sh
export tenant=`tenant root`
export rootTenant=$tenant
export project=sim
echoit() {
  echo $*
}
run() {
  echo $*
  $*
}
source subs/volume

export varray=VPLEX+FNM00130900300_FNM00130900301_cluster1
export vpool=VPLEX+FNM00130900300_FNM00130900301_cluster1_Local
cg=""
export volcount=100

#vnames="v00 v01 v02 v03 v04 v05 v06 v07 v08 v09 v10 v11 v12 v13 v14 v15 v16 v17 v18 v19 v20 v21 v21 v22 v23 v24 v25 v26 v27 v28 v29 v30 v31 v32 v33 v34"
vnames="v38 v39 v40 v41 v42"
for vname in $vnames
do
volumes_create $vname $varray $vpool "" $volcount
done


