#!/usr/bin/python
#
# Copyright (c) 2015 EMC Corporation
# All Rights Reserved
#

import argparse
import sys
import os
from bourne import *

#----------------------------------------------------------------------
# datacenter cli functions
#----------------------------------------------------------------------

def datacenter_create(args):
    bourne.connect(args.ip)
    task = bourne.datacenter_create(args.label, args.vcenter)
    print task

def datacenter_delete(args):
    bourne.connect(args.ip)
    res = bourne.datacenter_delete(args.name)
    print res

def datacenter_show(args):
    bourne.connect(args.ip)
    datacenter = bourne.datacenter_show(args.name)
    print datacenter

def datacenter_query(args):
    bourne.connect(args.ip)
    print bourne.datacenter_query(args.name)

def datacenter_list(args):
    bourne.connect(args.ip)
    datacenter_display_hdr()
    res = bourne.datacenter_list(args.vcenter)
    vcenter = bourne.vcenter_query(args.vcenter)
    for r in res:
        datacenter = bourne.api('GET', r['link']['href'], None)
        datacenter_display(datacenter)

#
# display datacenter in list form
#
datacenter_display_fmt = '{0:16s} {1:6s} {2:65s} {3:s}'

def datacenter_display_hdr():
    print datacenter_display_fmt.format('name', 'active', 'vcenter', 'id')

def datacenter_display(datacenter):
    print datacenter_display_fmt.format(datacenter['name'],'NO' if datacenter['inactive'] else 'YES',
              datacenter['vcenter']['id'], datacenter['id'])

# tag
def datacenter_tag(args):
    bourne.connect(args.ip)
    if (args.id == None):
        args.id = bourne.datacenter_query(args.name)
    print 'Tagging datacenter', args.id
    bourne.tag(args.resource_type, args.id, args.tags)

# search
def datacenter_search(args):
    bourne.connect(args.ip)
    if (args.scope != None):
        # query tenant id from tenant name
        args.scope = bourne.tenant_query(args.scope)
    array = bourne.search(args.resource_type, args.scope, args.prefix, args.project, args.tag)
    print 'Searching datacenter with ' + args.prefix
    if (len(array) == 0):
        raise Exception('Failed to search with prefix ' + args.prefix)
    else:
        print 'Result: ', array

#----------------------------------------------------------------------
# command-line parsing
#----------------------------------------------------------------------

try:
    bourne_ip = os.environ['BOURNE_IPADDR']
except:
    bourne_ip = 'localhost'

# datacenter <cmd> <cmd_args>
parser = argparse.ArgumentParser(description = 'Bourne datacenter cli usage.')
parser.add_argument('cmd', help = 'cmd = (create | delete | show | list )')
parser.add_argument('--ip',	metavar = 'ipaddr',	help = 'IP address of bourne', default=bourne_ip)

# datacenter create label vcenter
create = argparse.ArgumentParser(parents = [parser], conflict_handler='resolve')
create.add_argument('label',            help = 'label for the datacenter')
create.add_argument('vcenter',          help = 'parent vcenter name', default = None)

# datacenter delete uri
delete = argparse.ArgumentParser(parents = [parser], conflict_handler='resolve')
delete.add_argument('name',	help = 'name of datacenter in the format vcenter_name/datacenter_name')

# datacenter show uri
show = argparse.ArgumentParser(parents = [parser], conflict_handler='resolve')
show.add_argument('name',	help = 'name of datacenter in the format vcenter_name/datacenter_name')

# datacenter query name vcenter
query = argparse.ArgumentParser(parents = [parser], conflict_handler='resolve')
query.add_argument('name',	help = 'name of datacenter in the format vcenter_name/datacenter_name')

# datacenter list vcenter
list = argparse.ArgumentParser(parents = [parser], conflict_handler='resolve')
list.add_argument('vcenter',	help = 'vcenter name', default = None)

# tag 
resource_type="datacenter"
tag = argparse.ArgumentParser(parents = [parser], conflict_handler='resolve')
tag.add_argument('--resource_type',   metavar = 'resource_type',     help = 'resource type', default=resource_type)
tag.add_argument('--id',     metavar = 'id',     help = 'resource id', default=None)
tag.add_argument('name',     metavar = 'name',   help = 'resource name')
tag.add_argument('tags',     metavar = 'tags',   help = 'tags', nargs='+', default=None)

# search
search = argparse.ArgumentParser(parents = [parser], conflict_handler='resolve')
search.add_argument('--resource_type',   metavar = 'resource_type',     help = 'resource type', default=resource_type)
search.add_argument('--scope',   metavar = 'scope',  help = 'scope(global or tenant) for searching', default=None)
search.add_argument('prefix',    metavar = 'prefix', help = 'prefix for search name or tag')
search.add_argument('--tag',     metavar = 'tag',    help = 'boolean for search tag or not (search from name)', default=None)
search.add_argument('--project', metavar = 'project',help = 'search name within project', default=None)


#----------------------------------------------------------------------
# Main script
#----------------------------------------------------------------------

try:
    if (len(sys.argv) > 1):
        cmd = sys.argv[1]
    else:
        cmd = None

    bourne = Bourne()

    if   (cmd == "create"):
        args = create.parse_args()
        datacenter_create(args)
    elif (cmd == "delete"):
        args = delete.parse_args()
        datacenter_delete(args)
    elif (cmd == "show"):
        args = show.parse_args()
        datacenter_show(args)
    elif (cmd == "query"):
        args = query.parse_args()
        datacenter_query(args)
    elif (cmd == "list"):
        args = list.parse_args()
        datacenter_list(args)
    elif(cmd == "tag"):
        args = tag.parse_args()
        datacenter_tag(args)
    elif (cmd == "search"):
        args = search.parse_args()
        datacenter_search(args)
    else:
        parser.print_help()
except:
    raise
