#!/usr/bin/python

#
# Copyright (c) 2012 EMC Corporation
# All Rights Reserved
#
# This software contains the intellectual property of EMC Corporation
# or is licensed to EMC Corporation from third parties.  Use of this
# software and the intellectual property contained therein is expressly
# limited to the terms and conditions of the License Agreement under which
# it is provided by or on behalf of EMC.
#

import argparse
import sys
import os
from bourne import Bourne

#----------------------------------------------------------------------
# monitor cli functions
#----------------------------------------------------------------------

def monitor_query(args):
    bourne.connect(args.ip)
    return bourne.monitor_query(args.timeslot, args.language);
    
#----------------------------------------------------------------------
# command-line parsing
#----------------------------------------------------------------------

try:
    bourne_ip = os.environ['BOURNE_IPADDR']
except:
    bourne_ip = 'localhost'

# security <cmd> <cmd_args>  [--ip ipaddr]
parser = argparse.ArgumentParser(description = 'Bourne Audit cli usage.')
parser.add_argument('cmd', help = 'cmd = ( query ) timeslot language')
parser.add_argument('--ip',	metavar = 'ipaddr',	help = 'IP address of bourne', default=bourne_ip)

# security login
query = argparse.ArgumentParser(parents = [parser], conflict_handler='resolve')
query.add_argument('timeslot',    help = 'time window of monitor logs. e.g. 2013-03-22T03 or 2013-03-22T03:28')
query.add_argument('language',    help = 'language of monitor logs. e.g. en_US')

try:

    if (len(sys.argv) > 1):
        cmd = sys.argv[1]
    else:
        cmd = None

    bourne = Bourne()

    if  (cmd == "query"):
        args = query.parse_args()
        monitor_query(args)
    else:
        parser.print_help()

except:
    raise
    
