#!/usr/bin/python
#
# Copyright (c) 2015 EMC Corporation
# All Rights Reserved
#

import argparse
import sys
import os
from bourne import *

#----------------------------------------------------------------------
# search cli functions
#----------------------------------------------------------------------

def search(args):
    bourne.connect(args.ip)
    resources = bourne.search(args.resource_type, args.scope, args.prefix, args.project, args.tag)
    print resources

#----------------------------------------------------------------------
# command-line parsing
#----------------------------------------------------------------------

try:
    bourne_ip = os.environ['BOURNE_IPADDR']
except:
    bourne_ip = 'localhost'

# search <cmd_args>
parser = argparse.ArgumentParser(description = 'Bourne search cli usage.')
parser.add_argument('--ip',metavar = 'ipaddr',help = 'IP address of bourne', default=bourne_ip)
parser.add_argument('--resource_type',	metavar = 'resource_type', help = 'resource type', required = True, default=None)
parser.add_argument('--scope', metavar = 'scope', help='global or tenant', default=None)
parser.add_argument('--prefix', metavar = 'prefix', help='prefix', default=None)
parser.add_argument('--project', metavar = 'project', help='project', default=None)
parser.add_argument('--tag', help='search tags', action="store_true")

#----------------------------------------------------------------------
# Main script
#----------------------------------------------------------------------

try:
    bourne = Bourne()
    args = parser.parse_args()
    search(args)

except:
    raise
