
package com.emc.storageos.vasa;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.0.3
 * 2015-10-01T14:11:45.076+05:30
 * Generated source version: 3.0.3
 */

@WebFault(name = "InactiveProvider", targetNamespace = "http://com.vmware.vim.vasa/2.0/xsd")
public class InactiveProvider_Exception extends java.lang.Exception {
    
    private com.emc.storageos.vasa.InactiveProvider2 inactiveProvider;

    public InactiveProvider_Exception() {
        super();
    }
    
    public InactiveProvider_Exception(String message) {
        super(message);
    }
    
    public InactiveProvider_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public InactiveProvider_Exception(String message, com.emc.storageos.vasa.InactiveProvider2 inactiveProvider) {
        super(message);
        this.inactiveProvider = inactiveProvider;
    }

    public InactiveProvider_Exception(String message, com.emc.storageos.vasa.InactiveProvider2 inactiveProvider, Throwable cause) {
        super(message, cause);
        this.inactiveProvider = inactiveProvider;
    }

    public com.emc.storageos.vasa.InactiveProvider2 getFaultInfo() {
        return this.inactiveProvider;
    }
}
