
package com.emc.storageos.vasa;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.0.3
 * 2015-10-01T14:11:45.155+05:30
 * Generated source version: 3.0.3
 */

@WebFault(name = "IncompatibleVolume", targetNamespace = "http://com.vmware.vim.vasa/2.0/xsd")
public class IncompatibleVolume_Exception extends java.lang.Exception {
    
    private com.emc.storageos.vasa.IncompatibleVolume2 incompatibleVolume;

    public IncompatibleVolume_Exception() {
        super();
    }
    
    public IncompatibleVolume_Exception(String message) {
        super(message);
    }
    
    public IncompatibleVolume_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public IncompatibleVolume_Exception(String message, com.emc.storageos.vasa.IncompatibleVolume2 incompatibleVolume) {
        super(message);
        this.incompatibleVolume = incompatibleVolume;
    }

    public IncompatibleVolume_Exception(String message, com.emc.storageos.vasa.IncompatibleVolume2 incompatibleVolume, Throwable cause) {
        super(message, cause);
        this.incompatibleVolume = incompatibleVolume;
    }

    public com.emc.storageos.vasa.IncompatibleVolume2 getFaultInfo() {
        return this.incompatibleVolume;
    }
}
