
package com.emc.storageos.vasa;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.0.3
 * 2015-10-01T14:11:45.209+05:30
 * Generated source version: 3.0.3
 */

@WebFault(name = "InvalidStatisticsContext", targetNamespace = "http://com.vmware.vim.vasa/2.0/xsd")
public class InvalidStatisticsContext_Exception extends java.lang.Exception {
    
    private com.emc.storageos.vasa.InvalidStatisticsContext2 invalidStatisticsContext;

    public InvalidStatisticsContext_Exception() {
        super();
    }
    
    public InvalidStatisticsContext_Exception(String message) {
        super(message);
    }
    
    public InvalidStatisticsContext_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public InvalidStatisticsContext_Exception(String message, com.emc.storageos.vasa.InvalidStatisticsContext2 invalidStatisticsContext) {
        super(message);
        this.invalidStatisticsContext = invalidStatisticsContext;
    }

    public InvalidStatisticsContext_Exception(String message, com.emc.storageos.vasa.InvalidStatisticsContext2 invalidStatisticsContext, Throwable cause) {
        super(message, cause);
        this.invalidStatisticsContext = invalidStatisticsContext;
    }

    public com.emc.storageos.vasa.InvalidStatisticsContext2 getFaultInfo() {
        return this.invalidStatisticsContext;
    }
}
