
package com.emc.storageos.vasa;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.0.3
 * 2015-10-01T14:11:45.216+05:30
 * Generated source version: 3.0.3
 */

@WebFault(name = "InvalidLogin", targetNamespace = "http://com.vmware.vim.vasa/2.0/xsd")
public class InvalidLogin_Exception extends java.lang.Exception {
    
    private com.emc.storageos.vasa.InvalidLogin2 invalidLogin;

    public InvalidLogin_Exception() {
        super();
    }
    
    public InvalidLogin_Exception(String message) {
        super(message);
    }
    
    public InvalidLogin_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public InvalidLogin_Exception(String message, com.emc.storageos.vasa.InvalidLogin2 invalidLogin) {
        super(message);
        this.invalidLogin = invalidLogin;
    }

    public InvalidLogin_Exception(String message, com.emc.storageos.vasa.InvalidLogin2 invalidLogin, Throwable cause) {
        super(message, cause);
        this.invalidLogin = invalidLogin;
    }

    public com.emc.storageos.vasa.InvalidLogin2 getFaultInfo() {
        return this.invalidLogin;
    }
}
