
package com.emc.storageos.vasa;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.0.3
 * 2015-10-01T14:11:45.117+05:30
 * Generated source version: 3.0.3
 */

@WebFault(name = "InvalidSession", targetNamespace = "http://com.vmware.vim.vasa/2.0/xsd")
public class InvalidSession_Exception extends java.lang.Exception {
    
    private com.emc.storageos.vasa.InvalidSession2 invalidSession;

    public InvalidSession_Exception() {
        super();
    }
    
    public InvalidSession_Exception(String message) {
        super(message);
    }
    
    public InvalidSession_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public InvalidSession_Exception(String message, com.emc.storageos.vasa.InvalidSession2 invalidSession) {
        super(message);
        this.invalidSession = invalidSession;
    }

    public InvalidSession_Exception(String message, com.emc.storageos.vasa.InvalidSession2 invalidSession, Throwable cause) {
        super(message, cause);
        this.invalidSession = invalidSession;
    }

    public com.emc.storageos.vasa.InvalidSession2 getFaultInfo() {
        return this.invalidSession;
    }
}
