
package com.emc.storageos.vasa;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.0.3
 * 2015-10-01T14:11:45.102+05:30
 * Generated source version: 3.0.3
 */

@WebFault(name = "InvalidArgument", targetNamespace = "http://com.vmware.vim.vasa/2.0/xsd")
public class InvalidArgument_Exception extends java.lang.Exception {
    
    private com.emc.storageos.vasa.InvalidArgument2 invalidArgument;

    public InvalidArgument_Exception() {
        super();
    }
    
    public InvalidArgument_Exception(String message) {
        super(message);
    }
    
    public InvalidArgument_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public InvalidArgument_Exception(String message, com.emc.storageos.vasa.InvalidArgument2 invalidArgument) {
        super(message);
        this.invalidArgument = invalidArgument;
    }

    public InvalidArgument_Exception(String message, com.emc.storageos.vasa.InvalidArgument2 invalidArgument, Throwable cause) {
        super(message, cause);
        this.invalidArgument = invalidArgument;
    }

    public com.emc.storageos.vasa.InvalidArgument2 getFaultInfo() {
        return this.invalidArgument;
    }
}
