
package com.emc.storageos.vasa;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.0.3
 * 2015-10-01T14:11:45.136+05:30
 * Generated source version: 3.0.3
 */

@WebFault(name = "LostEvent", targetNamespace = "http://com.vmware.vim.vasa/2.0/xsd")
public class LostEvent_Exception extends java.lang.Exception {
    
    private com.emc.storageos.vasa.LostEvent2 lostEvent;

    public LostEvent_Exception() {
        super();
    }
    
    public LostEvent_Exception(String message) {
        super(message);
    }
    
    public LostEvent_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public LostEvent_Exception(String message, com.emc.storageos.vasa.LostEvent2 lostEvent) {
        super(message);
        this.lostEvent = lostEvent;
    }

    public LostEvent_Exception(String message, com.emc.storageos.vasa.LostEvent2 lostEvent, Throwable cause) {
        super(message, cause);
        this.lostEvent = lostEvent;
    }

    public com.emc.storageos.vasa.LostEvent2 getFaultInfo() {
        return this.lostEvent;
    }
}
