
package com.emc.storageos.vasa;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.0.3
 * 2015-10-01T14:11:45.178+05:30
 * Generated source version: 3.0.3
 */

@WebFault(name = "NotCancellable", targetNamespace = "http://com.vmware.vim.vasa/2.0/xsd")
public class NotCancellable_Exception extends java.lang.Exception {
    
    private com.emc.storageos.vasa.NotCancellable2 notCancellable;

    public NotCancellable_Exception() {
        super();
    }
    
    public NotCancellable_Exception(String message) {
        super(message);
    }
    
    public NotCancellable_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public NotCancellable_Exception(String message, com.emc.storageos.vasa.NotCancellable2 notCancellable) {
        super(message);
        this.notCancellable = notCancellable;
    }

    public NotCancellable_Exception(String message, com.emc.storageos.vasa.NotCancellable2 notCancellable, Throwable cause) {
        super(message, cause);
        this.notCancellable = notCancellable;
    }

    public com.emc.storageos.vasa.NotCancellable2 getFaultInfo() {
        return this.notCancellable;
    }
}
