
package com.emc.storageos.vasa;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.0.3
 * 2015-10-01T14:11:45.143+05:30
 * Generated source version: 3.0.3
 */

@WebFault(name = "NotFound", targetNamespace = "http://com.vmware.vim.vasa/2.0/xsd")
public class NotFound_Exception extends java.lang.Exception {
    
    private com.emc.storageos.vasa.NotFound2 notFound;

    public NotFound_Exception() {
        super();
    }
    
    public NotFound_Exception(String message) {
        super(message);
    }
    
    public NotFound_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public NotFound_Exception(String message, com.emc.storageos.vasa.NotFound2 notFound) {
        super(message);
        this.notFound = notFound;
    }

    public NotFound_Exception(String message, com.emc.storageos.vasa.NotFound2 notFound, Throwable cause) {
        super(message, cause);
        this.notFound = notFound;
    }

    public com.emc.storageos.vasa.NotFound2 getFaultInfo() {
        return this.notFound;
    }
}
