
package com.emc.storageos.vasa;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.0.3
 * 2015-10-01T14:11:45.124+05:30
 * Generated source version: 3.0.3
 */

@WebFault(name = "NotImplemented", targetNamespace = "http://com.vmware.vim.vasa/2.0/xsd")
public class NotImplemented_Exception extends java.lang.Exception {
    
    private com.emc.storageos.vasa.NotImplemented2 notImplemented;

    public NotImplemented_Exception() {
        super();
    }
    
    public NotImplemented_Exception(String message) {
        super(message);
    }
    
    public NotImplemented_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public NotImplemented_Exception(String message, com.emc.storageos.vasa.NotImplemented2 notImplemented) {
        super(message);
        this.notImplemented = notImplemented;
    }

    public NotImplemented_Exception(String message, com.emc.storageos.vasa.NotImplemented2 notImplemented, Throwable cause) {
        super(message, cause);
        this.notImplemented = notImplemented;
    }

    public com.emc.storageos.vasa.NotImplemented2 getFaultInfo() {
        return this.notImplemented;
    }
}
