
package com.emc.storageos.vasa;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.0.3
 * 2015-10-01T14:11:45.172+05:30
 * Generated source version: 3.0.3
 */

@WebFault(name = "OutOfResource", targetNamespace = "http://com.vmware.vim.vasa/2.0/xsd")
public class OutOfResource_Exception extends java.lang.Exception {
    
    private com.emc.storageos.vasa.OutOfResource2 outOfResource;

    public OutOfResource_Exception() {
        super();
    }
    
    public OutOfResource_Exception(String message) {
        super(message);
    }
    
    public OutOfResource_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public OutOfResource_Exception(String message, com.emc.storageos.vasa.OutOfResource2 outOfResource) {
        super(message);
        this.outOfResource = outOfResource;
    }

    public OutOfResource_Exception(String message, com.emc.storageos.vasa.OutOfResource2 outOfResource, Throwable cause) {
        super(message, cause);
        this.outOfResource = outOfResource;
    }

    public com.emc.storageos.vasa.OutOfResource2 getFaultInfo() {
        return this.outOfResource;
    }
}
