
package com.emc.storageos.vasa;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.0.3
 * 2015-10-01T14:11:45.161+05:30
 * Generated source version: 3.0.3
 */

@WebFault(name = "PermissionDenied", targetNamespace = "http://com.vmware.vim.vasa/2.0/xsd")
public class PermissionDenied_Exception extends java.lang.Exception {
    
    private com.emc.storageos.vasa.PermissionDenied2 permissionDenied;

    public PermissionDenied_Exception() {
        super();
    }
    
    public PermissionDenied_Exception(String message) {
        super(message);
    }
    
    public PermissionDenied_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public PermissionDenied_Exception(String message, com.emc.storageos.vasa.PermissionDenied2 permissionDenied) {
        super(message);
        this.permissionDenied = permissionDenied;
    }

    public PermissionDenied_Exception(String message, com.emc.storageos.vasa.PermissionDenied2 permissionDenied, Throwable cause) {
        super(message, cause);
        this.permissionDenied = permissionDenied;
    }

    public com.emc.storageos.vasa.PermissionDenied2 getFaultInfo() {
        return this.permissionDenied;
    }
}
