
package com.emc.storageos.vasa;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.0.3
 * 2015-10-01T14:11:45.197+05:30
 * Generated source version: 3.0.3
 */

@WebFault(name = "SnapshotTooMany", targetNamespace = "http://com.vmware.vim.vasa/2.0/xsd")
public class SnapshotTooMany_Exception extends java.lang.Exception {
    
    private com.emc.storageos.vasa.SnapshotTooMany2 snapshotTooMany;

    public SnapshotTooMany_Exception() {
        super();
    }
    
    public SnapshotTooMany_Exception(String message) {
        super(message);
    }
    
    public SnapshotTooMany_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public SnapshotTooMany_Exception(String message, com.emc.storageos.vasa.SnapshotTooMany2 snapshotTooMany) {
        super(message);
        this.snapshotTooMany = snapshotTooMany;
    }

    public SnapshotTooMany_Exception(String message, com.emc.storageos.vasa.SnapshotTooMany2 snapshotTooMany, Throwable cause) {
        super(message, cause);
        this.snapshotTooMany = snapshotTooMany;
    }

    public com.emc.storageos.vasa.SnapshotTooMany2 getFaultInfo() {
        return this.snapshotTooMany;
    }
}
