
package com.emc.storageos.vasa;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.0.3
 * 2015-10-01T14:11:45.228+05:30
 * Generated source version: 3.0.3
 */

@WebFault(name = "Timeout", targetNamespace = "http://com.vmware.vim.vasa/2.0/xsd")
public class Timeout_Exception extends java.lang.Exception {
    
    private com.emc.storageos.vasa.Timeout2 timeout;

    public Timeout_Exception() {
        super();
    }
    
    public Timeout_Exception(String message) {
        super(message);
    }
    
    public Timeout_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public Timeout_Exception(String message, com.emc.storageos.vasa.Timeout2 timeout) {
        super(message);
        this.timeout = timeout;
    }

    public Timeout_Exception(String message, com.emc.storageos.vasa.Timeout2 timeout, Throwable cause) {
        super(message, cause);
        this.timeout = timeout;
    }

    public com.emc.storageos.vasa.Timeout2 getFaultInfo() {
        return this.timeout;
    }
}
