
package com.emc.storageos.vasa;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.0.3
 * 2015-10-01T14:11:45.222+05:30
 * Generated source version: 3.0.3
 */

@WebFault(name = "TooMany", targetNamespace = "http://com.vmware.vim.vasa/2.0/xsd")
public class TooMany_Exception extends java.lang.Exception {
    
    private com.emc.storageos.vasa.TooMany2 tooMany;

    public TooMany_Exception() {
        super();
    }
    
    public TooMany_Exception(String message) {
        super(message);
    }
    
    public TooMany_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public TooMany_Exception(String message, com.emc.storageos.vasa.TooMany2 tooMany) {
        super(message);
        this.tooMany = tooMany;
    }

    public TooMany_Exception(String message, com.emc.storageos.vasa.TooMany2 tooMany, Throwable cause) {
        super(message, cause);
        this.tooMany = tooMany;
    }

    public com.emc.storageos.vasa.TooMany2 getFaultInfo() {
        return this.tooMany;
    }
}
