
package com.emc.storageos.vasa;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.0.3
 * 2015-10-01T14:11:45.109+05:30
 * Generated source version: 3.0.3
 */

@WebFault(name = "VasaProviderBusy", targetNamespace = "http://com.vmware.vim.vasa/2.0/xsd")
public class VasaProviderBusy_Exception extends java.lang.Exception {
    
    private com.emc.storageos.vasa.VasaProviderBusy2 vasaProviderBusy;

    public VasaProviderBusy_Exception() {
        super();
    }
    
    public VasaProviderBusy_Exception(String message) {
        super(message);
    }
    
    public VasaProviderBusy_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public VasaProviderBusy_Exception(String message, com.emc.storageos.vasa.VasaProviderBusy2 vasaProviderBusy) {
        super(message);
        this.vasaProviderBusy = vasaProviderBusy;
    }

    public VasaProviderBusy_Exception(String message, com.emc.storageos.vasa.VasaProviderBusy2 vasaProviderBusy, Throwable cause) {
        super(message, cause);
        this.vasaProviderBusy = vasaProviderBusy;
    }

    public com.emc.storageos.vasa.VasaProviderBusy2 getFaultInfo() {
        return this.vasaProviderBusy;
    }
}
