#!/bin/bash -e
#
# Copyright (c) 2016 EMC Corporation
# All Rights Reserved
#
# /etc/datatool
# 
# Manage data versioning for DR standby site, where we need maintain multiple 
# data copies. We use a major and minor version to identify versions - 
#
# Major version - a data copy starts from scratch(an empty folder). A unique 
# number is used to identify as a major version. Its content is fetched
# from active site. 
#
# Minor version - we may need make local changes to a data copy when losing 
# connections to active site(e.g zookeeper). We don't want to stain the 
# major version because we still want to be back later, so another concept
# "minor version" is introduced as a writable copy on standby site. It is 
# based on an major data copy. It uses a sequence number to identify itself.
# The original major version is named as 'base'. You can create a new minor 
# version, or revert back to base version, or set current minor version as
# base(a.k.a rebase). Currently we use minor version for zookeeper only.
#
# A minor version is discarded when reboot, or reconnecting to active site
#
# Data major and minor version combinedly together can be used to
# identify a data version. A version which is actively used and linked to 
# main dir as soft link. 


export PATH=/bin:/bin:/sbin:/usr/bin:/usr/sbin

_usage() {
    set +Ex
    echo "Usage: $0 --list"             >&2
    echo "   or: $0 --set-version datadir version"             >&2
    echo "   or: $0 --create-minor-version datadir" >&2
    echo "   or: $0 --revert-minor-version datadir"   >&2
    echo "   or: $0 --rebase-minor-version datadir"   >&2
    echo "   or: $0 --purge-unused-versions datadir"     >&2
    exit 2
}

_info() {
    echo "$0: Info: $*" >&2
}

_warn() {
    echo "$0: Warning: $*" >&2
}

_fatal() {
    set +Ex
    echo "$0: Error: $*" >&2
    exit 1
}

_err_handler() {
    set +E
    _fatal "Line ${LINENO}: $(eval echo \"${BASH_COMMAND}\")"
}

_exit_handler() {
    set +E
    for action in "${on_exit_actions[@]}" ; do
        eval "${action}"
    done
}

_set_on_exit() {
    on_exit_actions=( "${@}" "${on_exit_actions[@]}" )
}

_exit_handler() {
     set +E
     for action in "${on_exit_actions[@]}" ; do 
         eval "${action}"
     done
}

_set_traps() {
     declare -a on_exit_actions
     trap '' SIGINT
     trap '' SIGTERM
     trap _exit_handler EXIT
     trap 'set +Ex ; _fatal "Line ${LINENO}: $(eval echo \"${BASH_COMMAND}\")"' ERR
     if [ -n "${*}" ] ; then set "${@}" ; fi
}

lock_file=/tmp/${0##*/}.lock
lock_timeout=${lock_timeout:-30}

_x() {
    ( _set_traps -E && flock -x -w "${lock_timeout}" 200 && "${@}"  ) 200>${lock_file}
}


_get_major_version() {
    local dir=$(readlink ${1})
    local dirname=$(basename ${dir})
    local ver=$(echo ${dirname} | cut -d. -f1)
    echo ${ver}
}

_get_minor_version() {
    dir=$(readlink ${1})
    dirname=$(basename ${dir})
    local sn=$(echo ${dirname} | cut -d. -f2)
    echo ${sn}
}

_get_base_minor_version() {
    local basedir=$(dirname $1)

    if [ "$2" == "" ] ; then
	if [ ! -L $1 ] ; then
            _info "Versioning not supported for $1"
            return
	fi
        local curmaj=$(_get_major_version $1)
    else
        local curmaj="$2"
    fi

    local basesn=""
    for i in $(ls ${basedir}); do
        local dir=${basedir}/${i}
        [ -L ${dir} ] && continue;
	[ -f ${dir} ] && continue;
        local ver=$(echo ${i} | cut -d. -f1)
        [ "${ver}" != "${curmaj}" ] && continue;
        local sn=$(echo ${i} | cut -d. -f2)
        if [ "${basesn}" == "" ] ; then
            basesn=${sn}
        fi
        if [ "${sn}" -lt "${basesn}" ] ; then
            basesn=${sn}
        fi
    done
    echo "${basesn}"
}

# List all major/minor version for given data dir
_list() {
    local basedir=$(dirname $1)
    if [ ! -L $1 ] ; then
        _info "Versioning not supported for $1"
        return
    fi

    local curmaj=$(_get_major_version $1)
    for i in $(ls ${basedir}); do
        local dir=${basedir}/${i}
        [ -L ${dir} ] && continue;
	[ -f ${dir} ] && continue;
        local ver=$(echo ${i} | cut -d. -f1)
        [ -z "${ver}" ] && continue;
        local sn=$(echo ${i} | cut -d. -f2)
        if [ "${curmaj}" == "${ver}" ] ; then
            _info "ACTIVE - Major version(${ver}), minor (${sn})"
        else
            _info "UNUSED - Major version(${ver}), minor (${sn})"
        fi
    done
}

# Link data dir to given version. New dir is created if given version 
# doesn't exist on disk
_set_version() {
    local basedir=$(dirname $1)

    # check if version matched
    if [ -L $1 ] ; then
        local ver=$(_get_major_version $1)
        if [ "$2" == "${ver}" ] ; then
            # nothing to do if the pointer is linked to expected revision
            return
        fi
	unlink $1
    else
        # convert dir to softlink
        mv $1 ${basedir}/0.0
    fi

    # create new target revision dir if it does not exist
    local sn=0
    local basesn=$(_get_base_minor_version $1 $2) # get base
    [ "${basesn}" != "" ] && sn="${basesn}"
    local datadir="${basedir}/${2}.${sn}"
    if [ ! -d "${datadir}" ] ; then
        mkdir ${datadir}
        chown storageos:storageos ${datadir}
    fi

    # change the pointer to target revision. 
    ln -s ${datadir} $1
    chown -h storageos:storageos $1
}

# Purge unused major/minor version for given data dir
_purge_unused_versions() {
    local basedir=$(dirname $1)
    if [ ! -L $1 ] ; then
        # mutliple data reversion not supported yet
        return
    fi

    local curmaj=$(_get_major_version $1)
    for i in $(ls ${basedir}); do
        local dir=${basedir}/${i}
        [ -L ${dir} ] && continue;
	[ -f ${dir} ] && continue;
        local ver=$(echo ${i} | cut -d. -f1)
        [ -z "${ver}" ] && continue;
        if [ "${ver}" != "${curmaj}" ] ; then
            _info "Purging unused data dir ${i}"
	    rm -fR ${dir}
        fi
    done
}

# create a new minor version from base
_create_minor_version() {
    local basedir=$(dirname $1)	
    if [ ! -L $1 ]; then
        # convert dir to softlink
        mv $1 ${basedir}/0.0
        ln -s ${basedir}/0.0 $1
    fi
 
    local ver=$(_get_major_version $1)
    local sn=$(_get_minor_version $1)
    local nextsn=$((sn + 1))
    local basesn=$(_get_base_minor_version $1)

    # save off a golden zk copy
    cp -rp ${basedir}/${ver}.${basesn} ${basedir}/${ver}.${nextsn}
    unlink $1
    ln -s ${basedir}/${ver}.${nextsn} $1
    chown -h storageos:storageos ${1}
    if [ "${sn}" != "${basesn}" ]; then
       rm -fR ${basedir}/${ver}.${sn}
    fi
}

# discard minor version and revert to base
_revert_minor_version() {
    local basedir=$(dirname $1)
    local ver=$(_get_major_version $1)
    local sn=$(_get_minor_version $1)
    local basesn=$(_get_base_minor_version $1)
    if [ "${sn}" == "${basesn}" ]; then
        return
    fi
    if [ ! -d ${basedir}/${ver}.${basesn} ]; then
        _fatal "Failed to revert minor for $1: base ${basesn} missing"
    fi    

    unlink $1
    ln -s ${basedir}/${ver}.${basesn} $1
    chown -h storageos:storageos ${1}
    rm -fR ${basedir}/${ver}.${sn}
}

# set current minor version as base 
_rebase_minor_version() {
    local basedir=$(dirname $1)
    if [ ! -L $1 ] ; then
        # mutliple data reversion not supported yet
        return
    fi

    local curmaj=$(_get_major_version $1)
    local cursn=$(_get_minor_version $1)
    for i in $(ls ${basedir}); do
        local dir=${basedir}/${i}
        [ -L ${dir} ] && continue;
	[ -f ${dir} ] && continue;
        local ver=$(echo ${i} | cut -d. -f1)
        local sn=$(echo ${i} | cut -d. -f2)
	# skip other versions
        [ "${ver}" != "${curmaj}" ] && continue; 
        if [ "${sn}" -lt "${cursn}" ] ; then
            _info "Purging unused data dir ${i}"
	    rm -fR ${dir}
        fi
    done
}

# Parse options
#_set_traps -E
case ${#} in
    2)  case ${1} in
            --list)                   _x _list "${2}" ;;
            --create-minor-version)        _x _create_minor_version  "${2}" ;;
            --revert-minor-version)        _x _revert_minor_version  "${2}" ;;
            --rebase-minor-version)        _x _rebase_minor_version  "${2}" ;;
            --purge-unused-versions)  _x _purge_unused_versions "${2}" ;;
            *)                        _usage
        esac;;
    3)  case ${1} in 
            --set-version)             _x _set_version  "${2}" "${3}" ;;
            *)                        _usage
        esac;;
    *)  _usage
esac
