#!/bin/bash

### BEGIN INIT INFO
# Provides:          ECOM80
# Required-Start:    SimService iptables
# Required-Stop:
# Should-Stop:
# Default-Start:     3 5
# Default-Stop:
# Description:       starts ECOM80 simulator
### END INIT INFO
#. /etc/rc.d/init.d/functions
. /lib/lsb/init-functions
. /etc/rc.status

RETVAL=0
ECOM_HOME=/data/simulators/ecom80
DELAY=60
ECOM80disable="/var/log/ECOM80enable"


start() {
  #if [ ! -f $ECOM80disable ];then
        echo -n $"Starting ECOM80:..hold on 60sec .."
        ${ECOM_HOME}/bin/ECOM80  >/var/log/ECOM80.log 2>&1 &
        RETVAL=$?

        while [ $DELAY -gt 0 ]; do
        #echo "delay $DELAY"
  	if [ -f "${ECOM_HOME}/log/simulator-provider.log" ] ; then 
  	 START=`grep "ECOM has started" /var/log/ECOM80.log`
           if [ "${START}" != "" ] ; then
             echo "${START}" >> /var/log/ECOM80.log 2>&1            
             echo "..OK"
             return
           fi
          fi
        sleep 2
        DELAY=$((DELAY -1))
       done

       echo "Failed to start in 60 sec..try manual start" >> /var/log/ECOM80.log 2>&1
  #fi
}

stop() {

        echo -n $"Stopping ECOM80: "
	rm -f ${ECOM_HOME}/log/* >>/var/log/ECOM80.log 2>&1
        killproc  -TERM ECOM80 >> /var/log/ECOM80.log 2>&1
        RETVAL=$?
	echo  "..Done"
}



case "$1" in
  start)
        start
        ;;
  stop)
        stop
        ;;
  status)
        cnt=`pgrep -f "ECOM80" |wc -l`
        if(test $cnt -gt 3) ;
        then
                echo "ECOM80 simulator already running..."
        else
                echo "ECOM80 simulator not running."
        fi
    #    rc_status -v

        ;;

  *)
        echo $"Usage: ECOM80 {start|stop}"
        exit 1
        exit 1
esac


exit $RETVAL

# copy this script to /etc/init.d

# edit /etc/init.d/ECOM and change the ECOM_HOME=/temp/ecom to where ever you have installed simulator
# 
# chkconfig --add ECOM
# chkconfig ECOM on

# service ECOM start or stop or staus should now work
#  /var/log/ECOM.log should have the start log
# reboot should automatically start service

