#!/bin/sh
[ $# -eq 1 ] || {
    echo "Usage: duvalidation true|false : where true does validation and false does not"
    exit 2
}
# config/properties/?
source /root/tom.sh
echo $te/syssvc $sconf/sanity.conf 127.0.0.1 set_prop validation_check $1
$te/syssvc $sconf/sanity.conf 127.0.0.1 set_prop validation_check $1
echo $?
